lang: zig
config_name: lvgl_benchmark_zig
description: "LVGL rendering benchmark (Zig)"
zig:
  src_dir: src
  lib_name: lvgl_benchmark_zig
c_sources:
  - ../../c/lvgl_benchmark/src/benchmark_perf.c
  - ../../c/lvgl_benchmark/src/assets/benchmark_cogwheel_rgb.c
  - ../../c/lvgl_benchmark/src/assets/benchmark_cogwheel_argb.c
  - ../../c/lvgl_benchmark/src/assets/benchmark_avatar.c
c_includes:
  - ../../c/lvgl_benchmark/include
defconfig:
  - CONFIG_OVE_BSP=y
  - CONFIG_OVE_LVGL=y
  - CONFIG_OVE_TIMER=y
