PROJECT_NAME           = "oveRTOS C++ API"
PROJECT_BRIEF          = "C++20 RAII wrappers for the oveRTOS C API"
INPUT                  = bindings/cpp/ove docs-site/doxygen/doxygen-cpp-mainpage.md
USE_MDFILE_AS_MAINPAGE = docs-site/doxygen/doxygen-cpp-mainpage.md
RECURSIVE              = YES
FILE_PATTERNS          = *.hpp
EXTENSION_MAPPING      = hpp=C++
OUTPUT_DIRECTORY       = output/docs/doxygen-cpp
GENERATE_HTML          = YES
GENERATE_XML           = YES
GENERATE_LATEX         = NO
HTML_OUTPUT            = html
EXTRACT_ALL            = NO
EXTRACT_STATIC         = YES
OPTIMIZE_OUTPUT_FOR_C  = NO
SORT_MEMBER_DOCS       = NO
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = YES
PREDEFINED             = OVE_HEAP_THREAD=1 \
                         OVE_HEAP_MUTEX=1 \
                         OVE_HEAP_SEM=1 \
                         OVE_HEAP_EVENT=1 \
                         OVE_HEAP_CONDVAR=1 \
                         OVE_HEAP_QUEUE=1 \
                         OVE_HEAP_TIMER=1 \
                         OVE_HEAP_STREAM=1 \
                         OVE_HEAP_EVENTGROUP=1 \
                         OVE_HEAP_WORKQUEUE=1 \
                         CONFIG_OVE_QUEUE=1 \
                         CONFIG_OVE_TIMER=1 \
                         CONFIG_OVE_EVENTGROUP=1 \
                         OVE_HEAP_FS=1 \
                         OVE_HEAP_WATCHDOG=1 \
                         CONFIG_OVE_SYNC=1 \
                         CONFIG_OVE_AUDIO=1 \
                         CONFIG_OVE_FS=1 \
                         CONFIG_OVE_LVGL=1 \
                         CONFIG_OVE_NVS=1 \
                         CONFIG_OVE_SHELL=1 \
                         CONFIG_OVE_WATCHDOG=1 \
                         CONFIG_OVE_BSP=1 \
                         CONFIG_OVE_BOARD=1 \
                         CONFIG_OVE_GPIO=1 \
                         CONFIG_OVE_LED=1 \
                         CONFIG_OVE_TIME=1 \
                         CONFIG_OVE_CONSOLE=1 \
                         CONFIG_OVE_STREAM=1 \
                         CONFIG_OVE_WORKQUEUE=1
EXPAND_ONLY_PREDEF     = YES
WARN_IF_UNDOCUMENTED   = YES
WARN_IF_DOC_ERROR      = YES
