#!/usr/bin/env python3

# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""Board Import & Sync Tool for oveRTOS.

Subcommands:
    import zephyr  --board <name>  [--zephyr-base <path>] [--ove-name <name>]
    import nuttx   --board <name>  [--nuttx-base <path>]  [--config <variant>] [--ove-name <name>]
    sync           --board <name>  [--rtos zephyr|nuttx|all] [--merge|--force]
    list

Examples:
    board_tool.py import zephyr --board stm32f746g_disco
    board_tool.py import nuttx  --board stm32f746g-disco --config nsh
    board_tool.py sync   --board stm32f746g-discovery --rtos all
    board_tool.py list
"""

import argparse
import copy
import datetime
import json
import os
import re
import sys
import textwrap

try:
    import yaml
except ImportError:
    print("Error: pyyaml not installed. Install with: pip install pyyaml")
    sys.exit(1)

try:
    import jsonschema
except ImportError:
    print("Error: jsonschema not installed. Install with: pip install jsonschema")
    sys.exit(1)

try:
    from jinja2 import Environment, FileSystemLoader
except ImportError:
    print("Error: jinja2 not installed. Install with: pip install jinja2")
    sys.exit(1)


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------

def ove_dir():
    """Return OVE_DIR from env or derive from script location."""
    return os.environ.get(
        "OVE_DIR",
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    )


def boards_dir():
    return os.path.join(ove_dir(), "boards")


def dl_dir():
    return os.path.join(ove_dir(), "dl")


# ---------------------------------------------------------------------------
# BoardYaml helper
# ---------------------------------------------------------------------------

AUTO_BEGIN = "# Auto-generated by board_tool.py -- BEGIN"
AUTO_END = "# Auto-generated by board_tool.py -- END"

# C-style variant for .overlay / .conf
AUTO_BEGIN_C = "/* Auto-generated by board_tool.py -- BEGIN */"
AUTO_END_C = "/* Auto-generated by board_tool.py -- END */"


class BoardYaml:
    """Load, validate, save, and merge board.yaml files."""

    def __init__(self, data=None, path=None):
        self.data = data or {}
        self.path = path

    # -- I/O ----------------------------------------------------------------

    @classmethod
    def load(cls, path):
        with open(path, "r") as f:
            data = yaml.safe_load(f) or {}
        return cls(data=data, path=path)

    def save(self, path=None):
        path = path or self.path
        dirname = os.path.dirname(path)
        if dirname:
            os.makedirs(dirname, exist_ok=True)
        # Strip _meta before validation, but keep it in the saved file
        data_to_save = self.data
        with open(path, "w") as f:
            yaml.dump(data_to_save, f, default_flow_style=False, sort_keys=False)
        self.path = path

    # -- Validation ---------------------------------------------------------

    def validate(self):
        schema = _load_schema()
        # Strip _meta for validation since it's not in the schema
        clean = {k: v for k, v in self.data.items() if k != "_meta"}
        try:
            jsonschema.validate(instance=clean, schema=schema)
        except jsonschema.ValidationError as e:
            print(f"Board YAML validation error: {e.message}")
            sys.exit(1)

    # -- Merge --------------------------------------------------------------

    def merge_from(self, other):
        """Section-level merge: keep existing sections, fill missing from *other*."""
        for key, val in other.data.items():
            if key == "_meta":
                continue
            if key not in self.data:
                self.data[key] = copy.deepcopy(val)


def _load_schema():
    schema_path = os.path.join(ove_dir(), "config", "schemas", "board_schema.json")
    with open(schema_path, "r") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Minimal DTS parser (for Zephyr import)
# ---------------------------------------------------------------------------

class DtsParser:
    """Best-effort DTS parser — extracts nodes and properties we care about.

    Does NOT handle full DTS semantics. Unknown constructs are skipped.
    """

    def __init__(self, text):
        self._text = text
        self._pos = 0

    # -- Public API ---------------------------------------------------------

    def parse(self):
        """Return a nested dict representing the DTS tree."""
        root = {"_props": {}, "_children": {}}
        self._skip_ws()
        while self._pos < len(self._text):
            self._skip_ws()
            if self._pos >= len(self._text):
                break
            # Skip /dts-v1/; or /plugin/;
            if self._peek_str("/dts-v1/") or self._peek_str("/plugin/"):
                self._skip_until(";")
                self._advance()  # skip ';'
                continue
            # Skip #include / /include/
            if self._peek_str("#include") or self._peek_str("/include/"):
                self._skip_line()
                continue
            # Root node or labeled node
            if self._peek_char() == "/" and self._peek_at(1) == " ":
                self._advance()  # skip '/'
                self._skip_ws()
                if self._peek_char() == "{":
                    self._advance()
                    self._parse_node_body(root)
                continue
            # Labeled node reference: &label { ... }
            if self._peek_char() == "&":
                self._advance()
                label = self._read_ident()
                self._skip_ws()
                if self._peek_char() == "{":
                    self._advance()
                    child = root["_children"].setdefault(
                        "&" + label, {"_props": {}, "_children": {}}
                    )
                    self._parse_node_body(child)
                else:
                    self._skip_until(";")
                    self._advance()
                continue
            # Skip anything else
            self._skip_line()
        return root

    # -- Node body parser ---------------------------------------------------

    def _parse_node_body(self, node):
        """Parse contents of { ... }; consuming the closing };"""
        while self._pos < len(self._text):
            self._skip_ws()
            if self._pos >= len(self._text):
                break
            c = self._peek_char()
            if c == "}":
                self._advance()
                self._skip_ws()
                if self._pos < len(self._text) and self._peek_char() == ";":
                    self._advance()
                return
            # Delete-property
            if self._peek_str("/delete-property/"):
                self._skip_until(";")
                self._advance()
                continue
            # Delete-node
            if self._peek_str("/delete-node/"):
                self._skip_until(";")
                self._advance()
                continue
            # #include inside node
            if self._peek_str("#include"):
                self._skip_line()
                continue
            # Preprocessor directives (e.g., #define)
            if c == "#":
                self._skip_line()
                continue
            # Property or child node — read identifier
            # Labels: "label: node@addr { ... };"
            # Could also be "prop = ..." or "prop;" (boolean)
            ident = self._read_node_name_or_prop()
            if not ident:
                self._skip_line()
                continue
            self._skip_ws()

            # Check for label
            if self._peek_char() == ":":
                self._advance()  # skip ':'
                self._skip_ws()
                # After label, could be a node name
                ident2 = self._read_node_name_or_prop()
                if ident2:
                    ident = ident2
                    self._skip_ws()
                else:
                    # label: { ... } — use the label as node name
                    pass

            c = self._peek_char()
            if c == "{":
                # Child node
                self._advance()
                child = node["_children"].setdefault(
                    ident, {"_props": {}, "_children": {}}
                )
                self._parse_node_body(child)
            elif c == "=":
                # Property
                self._advance()
                self._skip_ws()
                val = self._read_property_value()
                node["_props"][ident] = val
                self._skip_ws()
                if self._pos < len(self._text) and self._peek_char() == ";":
                    self._advance()
            elif c == ";":
                # Boolean property
                node["_props"][ident] = True
                self._advance()
            else:
                self._skip_until(";")
                if self._pos < len(self._text):
                    self._advance()

    def _read_property_value(self):
        """Read a property value (string, cells, or phandle list)."""
        self._skip_ws()
        c = self._peek_char()
        if c == '"':
            return self._read_string()
        elif c == "<":
            return self._read_cells()
        elif c == "&":
            # phandle reference
            self._advance()
            ref = self._read_ident()
            return "&" + ref
        elif c == "[":
            # byte string
            return self._read_bytestring()
        else:
            # Could be a comma-separated list or unknown
            parts = []
            while self._pos < len(self._text) and self._peek_char() != ";":
                self._skip_ws()
                c = self._peek_char()
                if c == '"':
                    parts.append(self._read_string())
                elif c == "<":
                    parts.append(self._read_cells())
                elif c == "&":
                    self._advance()
                    parts.append("&" + self._read_ident())
                elif c == ",":
                    self._advance()
                else:
                    # raw token
                    tok = self._read_until_any(",; \t\n")
                    if tok:
                        parts.append(tok)
                    else:
                        break
            return parts if len(parts) != 1 else parts[0]

    def _read_string(self):
        """Read a quoted string."""
        if self._peek_char() != '"':
            return ""
        self._advance()
        start = self._pos
        while self._pos < len(self._text) and self._text[self._pos] != '"':
            if self._text[self._pos] == "\\":
                self._advance()
            self._advance()
        s = self._text[start : self._pos]
        if self._pos < len(self._text):
            self._advance()  # closing quote
        return s

    def _read_cells(self):
        """Read <cell0 cell1 ...> and return list of ints/strings."""
        if self._peek_char() != "<":
            return []
        self._advance()
        cells = []
        while self._pos < len(self._text) and self._peek_char() != ">":
            self._skip_ws()
            if self._pos >= len(self._text) or self._peek_char() == ">":
                break
            c = self._peek_char()
            if c == "&":
                self._advance()
                cells.append("&" + self._read_ident())
            elif c == "(":
                # Macro / expression — read until matching )
                expr = self._read_paren_expr()
                cells.append(expr)
            else:
                tok = self._read_until_any("> \t\n")
                if tok:
                    cells.append(self._try_int(tok))
        if self._pos < len(self._text) and self._peek_char() == ">":
            self._advance()
        return cells

    def _read_paren_expr(self):
        """Read a parenthesized expression, including nested parens."""
        depth = 0
        start = self._pos
        while self._pos < len(self._text):
            c = self._text[self._pos]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    self._advance()
                    return self._text[start : self._pos]
            self._advance()
        return self._text[start : self._pos]

    def _read_bytestring(self):
        """Read [xx xx ...] byte string."""
        if self._peek_char() != "[":
            return ""
        self._advance()
        start = self._pos
        while self._pos < len(self._text) and self._text[self._pos] != "]":
            self._advance()
        s = self._text[start : self._pos]
        if self._pos < len(self._text):
            self._advance()
        return s.strip()

    # -- Low-level helpers --------------------------------------------------

    def _read_ident(self):
        start = self._pos
        while self._pos < len(self._text) and (
            self._text[self._pos].isalnum()
            or self._text[self._pos] in "_-"
        ):
            self._advance()
        return self._text[start : self._pos]

    def _read_node_name_or_prop(self):
        """Read a DTS node name which can contain letters, digits, _ - , . @"""
        start = self._pos
        while self._pos < len(self._text) and (
            self._text[self._pos].isalnum()
            or self._text[self._pos] in "_-,.@+#"
        ):
            self._advance()
        return self._text[start : self._pos]

    def _read_until_any(self, chars):
        start = self._pos
        while self._pos < len(self._text) and self._text[self._pos] not in chars:
            self._advance()
        return self._text[start : self._pos]

    def _skip_ws(self):
        while self._pos < len(self._text):
            c = self._text[self._pos]
            if c in " \t\n\r":
                self._advance()
            elif c == "/" and self._pos + 1 < len(self._text):
                if self._text[self._pos + 1] == "/":
                    self._skip_line()
                elif self._text[self._pos + 1] == "*":
                    self._pos += 2
                    while self._pos + 1 < len(self._text):
                        if (
                            self._text[self._pos] == "*"
                            and self._text[self._pos + 1] == "/"
                        ):
                            self._pos += 2
                            break
                        self._advance()
                    else:
                        self._pos = len(self._text)
                else:
                    break
            else:
                break

    def _skip_line(self):
        while self._pos < len(self._text) and self._text[self._pos] != "\n":
            self._advance()
        if self._pos < len(self._text):
            self._advance()

    def _skip_until(self, char):
        while self._pos < len(self._text) and self._text[self._pos] != char:
            self._advance()

    def _peek_char(self):
        return self._text[self._pos] if self._pos < len(self._text) else ""

    def _peek_at(self, offset):
        p = self._pos + offset
        return self._text[p] if p < len(self._text) else ""

    def _peek_str(self, s):
        return self._text[self._pos : self._pos + len(s)] == s

    def _advance(self):
        self._pos += 1

    @staticmethod
    def _try_int(s):
        """Try to parse a token as an integer."""
        s = s.strip()
        if not s:
            return s
        try:
            if s.startswith("0x") or s.startswith("0X"):
                return int(s, 16)
            return int(s)
        except ValueError:
            return s


# ---------------------------------------------------------------------------
# DTS → board.yaml mapping (Zephyr import)
# ---------------------------------------------------------------------------

# Map vendor prefixes in root compatible to mcu_family slug
_MCU_FAMILY_MAP = {
    "st,stm32f7": "stm32f7",
    "st,stm32f4": "stm32f4",
    "st,stm32f3": "stm32f3",
    "st,stm32f1": "stm32f1",
    "st,stm32f0": "stm32f0",
    "st,stm32h7": "stm32h7",
    "st,stm32l4": "stm32l4",
    "st,stm32l0": "stm32l0",
    "st,stm32g0": "stm32g0",
    "st,stm32g4": "stm32g4",
    "st,stm32u5": "stm32u5",
    "st,stm32wb": "stm32wb",
    "st,stm32wl": "stm32wl",
    "nordic,nrf52": "nrf52",
    "nordic,nrf53": "nrf53",
    "nordic,nrf91": "nrf91",
    "espressif,esp32": "esp32",
    "nxp,imxrt": "imxrt",
    "nxp,lpc": "lpc",
    "atmel,sam": "sam",
    "raspberrypi,rp2040": "rp2040",
}


def _mcu_family_from_compatible(compat):
    """Derive mcu_family from the DTS root compatible string."""
    if isinstance(compat, list):
        compat = compat[0] if compat else ""
    for prefix, family in _MCU_FAMILY_MAP.items():
        if compat.startswith(prefix):
            return family
    # Fallback: strip vendor prefix
    if "," in compat:
        return compat.split(",", 1)[1].rstrip("0123456789").rstrip("-_")
    return compat


def _refine_nuttx_mcu_family(chip_dir, config):
    """Refine MCU family from NuttX defconfig beyond the chip directory name.

    The chip directory (e.g., boards/arm/stm32/<board>) is often too generic.
    This scans CONFIG_ARCH_CHIP_* boolean keys to extract the exact family.

    Examples:
        CONFIG_ARCH_CHIP_STM32F429Z=y → stm32f4
        CONFIG_ARCH_CHIP_NRF52840=y   → nrf52
    """
    # Collect candidates, prefer longer (more specific) suffixes
    candidates = []
    for key, val in config.items():
        if not key.startswith("CONFIG_ARCH_CHIP_") or val is not True:
            continue
        suffix = key[len("CONFIG_ARCH_CHIP_"):]
        if not suffix or len(suffix) <= 5:
            continue  # skip generic short names like "STM32"
        candidates.append(suffix)
    # Sort longest first so the most specific match wins
    candidates.sort(key=len, reverse=True)

    for suffix in candidates:
        # STM32 family: STM32F429Z → stm32f4, STM32H743XI → stm32h7
        m = re.match(r"STM32([A-Z])(\d)", suffix)
        if m:
            return f"stm32{m.group(1).lower()}{m.group(2)}"
        # Nordic: NRF52840 → nrf52, NRF5340 → nrf53
        m = re.match(r"NRF(\d{2})", suffix)
        if m:
            return f"nrf{m.group(1)}"
        # ESP: ESP32S3 → esp32
        if suffix.startswith("ESP32"):
            return "esp32"

    # Fall back to chip directory regex
    m = re.match(r"([a-zA-Z]+\d+[a-zA-Z]?\d*)", chip_dir)
    if m:
        return m.group(1).lower()
    return chip_dir


def _derive_nuttx_mcu(config, chip_dir):
    """Derive MCU identifier (e.g. STM32F429xx) from NuttX defconfig.

    Examples:
        CONFIG_ARCH_CHIP_STM32F429Z=y → STM32F429xx
        CONFIG_ARCH_CHIP_STM32F746ZG=y → STM32F746xx
        CONFIG_ARCH_CHIP_NRF52840=y   → NRF52840
    """
    # Collect candidates, prefer longest (most specific) suffix
    candidates = []
    for key, val in config.items():
        if not key.startswith("CONFIG_ARCH_CHIP_") or val is not True:
            continue
        suffix = key[len("CONFIG_ARCH_CHIP_"):]
        if not suffix or len(suffix) <= 5:
            continue  # skip generic short names like "STM32"
        candidates.append(suffix)
    candidates.sort(key=len, reverse=True)

    for suffix in candidates:
        # STM32: strip pin-count suffix letter(s), append xx
        m = re.match(r"(STM32[A-Z]\d{3,4})[A-Z]{1,2}$", suffix)
        if m:
            return m.group(1) + "xx"
        # Non-STM32 with enough specificity: return as-is
        return suffix

    # Fall back to CONFIG_ARCH_CHIP string value
    arch_chip = config.get("CONFIG_ARCH_CHIP", chip_dir)
    if isinstance(arch_chip, bool):
        return chip_dir
    return str(arch_chip)


def _extract_board_yaml_from_dts(tree, zephyr_board_name):
    """Build a board.yaml dict from parsed DTS tree.

    Returns (board_yaml_dict, warnings_list).
    """
    warnings = []
    data = {}

    props = tree.get("_props", {})
    children = tree.get("_children", {})

    # --- board identity ---
    compat = props.get("compatible", "")
    model = props.get("model", "")
    mcu_family = _mcu_family_from_compatible(compat)

    board_name = zephyr_board_name.replace("_", "-")
    mcu = ""
    if isinstance(compat, list):
        mcu = compat[0] if compat else ""
    elif isinstance(compat, str):
        mcu = compat
    # Try to make mcu a chip identifier
    if "," in mcu:
        mcu = mcu.split(",", 1)[1]

    data["board"] = {
        "name": board_name,
        "mcu_family": mcu_family,
        "mcu": mcu,
    }

    # --- memory ---
    memory = {}
    for name, node in children.items():
        if name.startswith("memory"):
            reg = node["_props"].get("reg", [])
            if isinstance(reg, list) and len(reg) >= 2:
                size = reg[-1]
                if isinstance(size, int) and size > 0:
                    memory["ram_kb"] = size // 1024
    # Flash: look in soc/flash-controller children
    soc = children.get("soc", {})
    if soc:
        for name, node in soc.get("_children", {}).items():
            if "flash" in name and "controller" in name:
                for cname, cnode in node.get("_children", {}).items():
                    if cname.startswith("flash"):
                        reg = cnode["_props"].get("reg", [])
                        if isinstance(reg, list) and len(reg) >= 2:
                            size = reg[-1]
                            if isinstance(size, int) and size > 0:
                                memory["flash_kb"] = size // 1024
    if memory:
        data["memory"] = memory
    warnings.append("clock.sysclk_mhz, clock.ahb_div, clock.apb1_div, clock.apb2_div need manual review (PLL config too complex for DTS extraction)")
    warnings.append("memory.dtcm_kb, memory.sdram_kb may need manual entry (secondary memory regions not always in base DTS)")

    # --- serial console ---
    chosen = children.get("chosen", {})
    chosen_props = chosen.get("_props", {}) if chosen else {}
    console_ref = chosen_props.get("zephyr,console", "")
    if isinstance(console_ref, str) and console_ref.startswith("&"):
        uart_label = console_ref[1:]
        uart_node = children.get("&" + uart_label, {})
        if not uart_node and soc:
            # Try to find in soc children
            for name, node in soc.get("_children", {}).items():
                if uart_label in name:
                    uart_node = node
                    break
        if uart_node:
            uart_props = uart_node.get("_props", {})
            baud = uart_props.get("current-speed", None)
            if isinstance(baud, list):
                baud = baud[0] if baud else None
            if isinstance(baud, int):
                data["serial"] = {"console": {"baud": baud}}
    warnings.append("serial.console.tx_pin, serial.console.rx_pin need manual review (pinctrl encoding is SoC-specific)")

    # --- LEDs ---
    leds_node = None
    for name, node in children.items():
        node_props = node.get("_props", {})
        node_compat = node_props.get("compatible", "")
        if node_compat == "gpio-leds" or name == "leds" or name == "gpio-leds":
            leds_node = node
            break
    if leds_node:
        led_list = []
        for led_name, led_node in leds_node.get("_children", {}).items():
            gpios = led_node.get("_props", {}).get("gpios", [])
            if isinstance(gpios, list) and len(gpios) >= 2:
                # gpios = <&gpioX pin flags>
                port_ref = gpios[0]
                pin = gpios[1] if len(gpios) > 1 else 0
                flags = gpios[2] if len(gpios) > 2 else 0
                port = _gpio_ref_to_port(port_ref)
                active_low = bool(isinstance(flags, int) and flags & 0x01)
                if isinstance(pin, int):
                    led_list.append({
                        "port": port,
                        "pin": pin,
                        "active_low": active_low,
                    })
        if led_list:
            data["leds"] = led_list

    # --- Audio codec ---
    # Look for i2c nodes containing codec children
    for name, node in children.items():
        if name.startswith("&i2c") or (soc and "i2c" in name):
            _search_codec(node, data)
    if soc:
        for name, node in soc.get("_children", {}).items():
            if "i2c" in name:
                _search_codec(node, data)
    warnings.append("audio.i2s.sample_rate, audio.i2s.channels need manual entry (application-level, not in DTS)")

    # --- Display ---
    for name, node in list(children.items()) + (
        list(soc.get("_children", {}).items()) if soc else []
    ):
        node_props = node.get("_props", {})
        if "ltdc" in name or "display" in name:
            w = node_props.get("width")
            h = node_props.get("height")
            if isinstance(w, list):
                w = w[0] if w else None
            if isinstance(h, list):
                h = h[0] if h else None
            if isinstance(w, int) and isinstance(h, int):
                data["display"] = {"width": w, "height": h}
                break
        # Also check children for panel nodes
        for cname, cnode in node.get("_children", {}).items():
            cp = cnode.get("_props", {})
            w = cp.get("width")
            h = cp.get("height")
            if isinstance(w, list):
                w = w[0] if w else None
            if isinstance(h, list):
                h = h[0] if h else None
            if isinstance(w, int) and isinstance(h, int):
                data["display"] = {"width": w, "height": h}
                break

    # --- SDMMC ---
    for name, node in (list(soc.get("_children", {}).items()) if soc else []):
        if "sdmmc" in name.lower() or "mmc" in name.lower():
            data["sdcard"] = {"interface": name.split("@")[0].upper().replace("-", "")}
            break

    # --- Clock (HSE) ---
    for name, node in children.items():
        node_props = node.get("_props", {})
        if "oscillator" in name or "hse" in name or "clk" in name:
            freq = node_props.get("clock-frequency")
            if isinstance(freq, list):
                freq = freq[0] if freq else None
            if isinstance(freq, int) and freq > 100000:
                data.setdefault("clock", {})["hse_freq_mhz"] = freq // 1000000
                break

    return data, warnings


def _gpio_ref_to_port(ref):
    """Convert a phandle like '&gpioi' to a port number (0=A, 1=B, ... 8=I)."""
    if isinstance(ref, str) and ref.startswith("&gpio"):
        suffix = ref[5:]
        if len(suffix) == 1 and suffix.isalpha():
            return ord(suffix.lower()) - ord("a")
    return 0


def _search_codec(node, data):
    """Search for audio codec child nodes in an I2C bus node."""
    for cname, cnode in node.get("_children", {}).items():
        cp = cnode.get("_props", {})
        compat = cp.get("compatible", "")
        reg = cp.get("reg", [])
        if "codec" in cname or "wm" in compat or "cs4" in compat or "tlv" in compat:
            codec_info = {}
            if compat:
                # Extract codec type from compatible string
                if "," in compat:
                    codec_info["type"] = compat.split(",", 1)[1].upper().replace("-", "")
                else:
                    codec_info["type"] = compat.upper()
            if isinstance(reg, list) and reg:
                addr = reg[0]
                if isinstance(addr, int):
                    codec_info["i2c_addr"] = f"0x{addr:02X}"
            if codec_info:
                data.setdefault("audio", {})["codec"] = codec_info


# ---------------------------------------------------------------------------
# Zephyr board discovery
# ---------------------------------------------------------------------------

def _find_zephyr_board_dir(zephyr_base, board_name):
    """Locate a Zephyr board directory (v3+ flat or v2 arch-based layout)."""
    # v3+: boards/<vendor>/<board>/
    boards_root = os.path.join(zephyr_base, "boards")
    if not os.path.isdir(boards_root):
        return None
    for vendor in os.listdir(boards_root):
        candidate = os.path.join(boards_root, vendor, board_name)
        if os.path.isdir(candidate):
            return candidate
    # v2: boards/<arch>/<board>/
    for arch in os.listdir(boards_root):
        candidate = os.path.join(boards_root, arch, board_name)
        if os.path.isdir(candidate):
            return candidate
    return None


def _read_dts_files(board_dir, board_name):
    """Read and concatenate DTS files for a Zephyr board."""
    # Try <board>.dts first, then <board_name>.dts
    dts_candidates = [
        os.path.join(board_dir, f"{board_name}.dts"),
        os.path.join(board_dir, f"{board_name}_defconfig"),
    ]
    # Also check for files matching the board name pattern
    if os.path.isdir(board_dir):
        for f in sorted(os.listdir(board_dir)):
            if f.endswith(".dts") and not f.endswith(".dtsi"):
                path = os.path.join(board_dir, f)
                if path not in dts_candidates:
                    dts_candidates.insert(0, path)

    dts_text = ""
    for path in dts_candidates:
        if os.path.isfile(path) and path.endswith(".dts"):
            with open(path, "r") as f:
                dts_text += f.read() + "\n"

    # Also read board-level DTSI includes (one level only)
    for f in sorted(os.listdir(board_dir)) if os.path.isdir(board_dir) else []:
        if f.endswith(".dtsi"):
            with open(os.path.join(board_dir, f), "r") as fp:
                dts_text += fp.read() + "\n"

    return dts_text


# ---------------------------------------------------------------------------
# NuttX board discovery & parsing
# ---------------------------------------------------------------------------

def parse_dotconfig(path):
    """Parse a Kconfig .config / defconfig file into a dict."""
    config = {}
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                if line.startswith("# CONFIG_") and line.endswith(" is not set"):
                    key = line.split()[1]
                    config[key] = False
                continue
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()
            if value == "y":
                config[key] = True
            elif value == "n":
                config[key] = False
            elif value.startswith('"') and value.endswith('"'):
                config[key] = value[1:-1]
            elif value.startswith("0x") or value.startswith("0X"):
                config[key] = int(value, 16)
            else:
                try:
                    config[key] = int(value)
                except ValueError:
                    config[key] = value
    return config


def _find_nuttx_board_dir(nuttx_base, board_name):
    """Locate a NuttX board directory: boards/<arch>/<chip>/<board>/"""
    boards_root = os.path.join(nuttx_base, "boards")
    if not os.path.isdir(boards_root):
        return None
    for arch in os.listdir(boards_root):
        arch_dir = os.path.join(boards_root, arch)
        if not os.path.isdir(arch_dir):
            continue
        for chip in os.listdir(arch_dir):
            candidate = os.path.join(arch_dir, chip, board_name)
            if os.path.isdir(candidate):
                return candidate
    return None


def _extract_board_yaml_from_nuttx(nuttx_board_dir, config_variant, board_name):
    """Build board.yaml dict from NuttX board directory.

    Returns (board_yaml_dict, warnings_list).
    """
    warnings = []
    data = {}

    # Derive mcu_family from path: boards/<arch>/<chip>/<board>
    parts = nuttx_board_dir.replace("\\", "/").split("/")
    chip = ""
    # Find the "boards" segment and extract chip
    for i, p in enumerate(parts):
        if p == "boards" and i + 2 < len(parts):
            chip = parts[i + 2]
            break

    # Parse defconfig
    defconfig_path = os.path.join(
        nuttx_board_dir, "configs", config_variant, "defconfig"
    )
    config = {}
    if os.path.isfile(defconfig_path):
        config = parse_dotconfig(defconfig_path)
    else:
        warnings.append(f"defconfig not found: {defconfig_path}")

    # Board identity — use refined helpers that scan CONFIG_ARCH_CHIP_* keys
    mcu_family = _refine_nuttx_mcu_family(chip, config)
    mcu = _derive_nuttx_mcu(config, chip)

    ove_name = board_name.replace("_", "-")
    data["board"] = {
        "name": ove_name,
        "mcu_family": mcu_family,
        "mcu": mcu,
    }

    # Memory
    memory = {}
    ram_size = config.get("CONFIG_RAM_SIZE")
    if isinstance(ram_size, int) and ram_size > 0:
        # Heuristic: values > 1024 are likely bytes, smaller values are likely KB
        memory["ram_kb"] = ram_size // 1024 if ram_size > 1024 else ram_size
        warnings.append(f"memory.ram_kb={memory['ram_kb']} — verify unit (CONFIG_RAM_SIZE={ram_size}, assumed {'bytes' if ram_size > 1024 else 'KB'})")
    flash_size = config.get("CONFIG_FLASH_SIZE")
    if isinstance(flash_size, int) and flash_size > 0:
        memory["flash_kb"] = flash_size // 1024 if flash_size > 1024 else flash_size
        warnings.append(f"memory.flash_kb={memory['flash_kb']} — verify unit (CONFIG_FLASH_SIZE={flash_size}, assumed {'bytes' if flash_size > 1024 else 'KB'})")
    if memory:
        data["memory"] = memory

    # Serial console
    for n in range(1, 9):
        key = f"CONFIG_USART{n}_SERIAL_CONSOLE"
        if config.get(key) is True:
            baud_key = f"CONFIG_USART{n}_BAUD"
            baud = config.get(baud_key)
            if isinstance(baud, int):
                data["serial"] = {"console": {"baud": baud}}
            break
    # Also check UART (not USART)
    if "serial" not in data:
        for n in range(0, 9):
            key = f"CONFIG_UART{n}_SERIAL_CONSOLE"
            if config.get(key) is True:
                baud_key = f"CONFIG_UART{n}_BAUD"
                baud = config.get(baud_key)
                if isinstance(baud, int):
                    data["serial"] = {"console": {"baud": baud}}
                break

    # Parse board.h for additional info
    board_h_path = os.path.join(nuttx_board_dir, "include", "board.h")
    if os.path.isfile(board_h_path):
        defines = _parse_board_h(board_h_path)

        # Clock
        clock = {}
        for key in ["BOARD_XTAL_FREQUENCY", "STM32_HSE_FREQUENCY"]:
            val = defines.get(key)
            if val and val > 100000:
                clock["hse_freq_mhz"] = val // 1000000
                break
        sysclk = defines.get("STM32_SYSCLK_FREQUENCY")
        if sysclk and sysclk > 100000:
            clock["sysclk_mhz"] = sysclk // 1000000
        if clock:
            data["clock"] = clock

        # Display
        w = defines.get("STM32_LTDC_WIDTH") or defines.get("BOARD_LCD_WIDTH")
        h = defines.get("STM32_LTDC_HEIGHT") or defines.get("BOARD_LCD_HEIGHT")
        if w and h:
            data["display"] = {"width": w, "height": h}

        # LED count
        nleds = defines.get("BOARD_NLEDS")
        if nleds and nleds > 0:
            data["leds"] = [{"port": 0, "pin": i, "active_low": False} for i in range(nleds)]
            warnings.append(f"leds: {nleds} LEDs detected from BOARD_NLEDS but port/pin need manual assignment")

    return data, warnings


def _parse_board_h(path):
    """Extract #define values from a board.h file. Returns dict of name→int."""
    defines = {}
    with open(path, "r") as f:
        for line in f:
            m = re.match(r"\s*#\s*define\s+(\w+)\s+(\S+)", line)
            if m:
                name = m.group(1)
                val_str = m.group(2)
                val = _try_parse_int(val_str)
                if val is not None:
                    defines[name] = val
    return defines


def _try_parse_int(s):
    """Try to parse a string as an integer (decimal or hex)."""
    s = s.strip().rstrip("UuLl")
    if not s:
        return None
    try:
        if s.startswith("0x") or s.startswith("0X"):
            return int(s, 16)
        return int(s)
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# Scaffold generation
# ---------------------------------------------------------------------------

def _render_scaffold(rtos, board_name, mcu_family, mcu, output_dir):
    """Render scaffold templates for a given RTOS into output_dir."""
    templates_dir = os.path.join(
        ove_dir(), "config", "templates", "board_scaffold", rtos
    )
    if not os.path.isdir(templates_dir):
        print(f"  Warning: no scaffold templates for {rtos}")
        return

    env = Environment(
        loader=FileSystemLoader(templates_dir),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )

    ctx = {
        "board_name": board_name,
        "mcu_family": mcu_family,
        "mcu": mcu,
    }

    os.makedirs(output_dir, exist_ok=True)
    for template_name in env.loader.list_templates():
        if not template_name.endswith(".j2"):
            continue
        output_name = template_name[:-3]  # strip .j2
        output_path = os.path.join(output_dir, output_name)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        template = env.get_template(template_name)
        content = template.render(**ctx)
        with open(output_path, "w") as f:
            f.write(content)
        print(f"  Created: {os.path.relpath(output_path, ove_dir())}")


# ---------------------------------------------------------------------------
# Sync: board.yaml → RTOS configs
# ---------------------------------------------------------------------------

def _sync_zephyr(board_yaml, board_dir, force=False):
    """Generate Zephyr .conf and .overlay from board.yaml."""
    data = board_yaml.data
    board_name = data["board"]["name"]
    # Prefer the original Zephyr board name from import metadata, then
    # check for existing .conf files in the boards/ subdirectory, and
    # finally fall back to deriving from the ove board name.
    meta = data.get("_meta", {})
    zephyr_name = meta.get("zephyr_board", None)
    if not zephyr_name:
        # Check for existing .conf files to discover the Zephyr name
        boards_subdir_check = os.path.join(board_dir, "zephyr", "boards")
        if os.path.isdir(boards_subdir_check):
            for f in os.listdir(boards_subdir_check):
                if f.endswith(".conf") and not f.startswith("."):
                    zephyr_name = f[: -len(".conf")]
                    break
    if not zephyr_name:
        zephyr_name = board_name.replace("-", "_")

    zephyr_dir = os.path.join(board_dir, "zephyr")
    if not os.path.isdir(zephyr_dir):
        print(f"  Skipping Zephyr sync: {zephyr_dir} does not exist")
        return

    boards_subdir = os.path.join(zephyr_dir, "boards")
    os.makedirs(boards_subdir, exist_ok=True)

    # --- .conf ---
    conf_path = os.path.join(boards_subdir, f"{zephyr_name}.conf")
    conf_lines = [AUTO_BEGIN]

    if "audio" in data:
        if "i2s" in data["audio"]:
            conf_lines.append("CONFIG_I2S=y")
            conf_lines.append("CONFIG_I2C=y")
            conf_lines.append("CONFIG_DMA=y")
            conf_lines.append("CONFIG_AUDIO=y")
        if "codec" in data["audio"]:
            conf_lines.append("CONFIG_AUDIO_CODEC=y")

    if "sdcard" in data:
        conf_lines.append("CONFIG_DISK_ACCESS=y")
        conf_lines.append("CONFIG_DISK_DRIVERS=y")
        conf_lines.append("CONFIG_DISK_DRIVER_SDMMC=y")

    if "display" in data:
        conf_lines.append("CONFIG_DISPLAY=y")

    ram_kb = data.get("memory", {}).get("ram_kb", 0)
    if ram_kb > 256:
        heap_size = min(ram_kb * 64, 262144)  # scale, cap at 256K
        conf_lines.append(f"CONFIG_HEAP_MEM_POOL_SIZE={heap_size}")

    conf_lines.append(AUTO_END)
    _write_file(conf_path, "\n".join(conf_lines) + "\n", force=force)
    print(f"  Synced: {os.path.relpath(conf_path, ove_dir())}")

    # --- .overlay ---
    overlay_path = os.path.join(boards_subdir, f"{zephyr_name}.overlay")
    overlay_lines = [AUTO_BEGIN_C]

    # LEDs overlay
    if "leds" in data and data["leds"]:
        overlay_lines.append("")
        overlay_lines.append("/ {")
        overlay_lines.append("\tleds {")
        overlay_lines.append('\t\tcompatible = "gpio-leds";')
        for i, led in enumerate(data["leds"]):
            port_letter = chr(ord("a") + led.get("port", 0))
            pin = led.get("pin", 0)
            flags = "GPIO_ACTIVE_LOW" if led.get("active_low") else "GPIO_ACTIVE_HIGH"
            overlay_lines.append(f"\t\tled_{i}: led_{i} {{")
            overlay_lines.append(f"\t\t\tgpios = <&gpio{port_letter} {pin} {flags}>;")
            overlay_lines.append(f"\t\t}};")
        overlay_lines.append("\t};")
        overlay_lines.append("};")

    # Serial console
    serial = data.get("serial", {}).get("console", {})
    baud = serial.get("baud")
    if baud:
        overlay_lines.append("")
        overlay_lines.append("/* TODO: verify USART instance — defaulting to usart1 */")
        overlay_lines.append(f"&usart1 {{")
        overlay_lines.append(f"\tcurrent-speed = <{baud}>;")
        overlay_lines.append(f'\tstatus = "okay";')
        overlay_lines.append(f"}};")

    # Audio codec
    codec = data.get("audio", {}).get("codec", {})
    if codec:
        addr_str = codec.get("i2c_addr", "0x1A")
        addr_int = int(addr_str, 16) if isinstance(addr_str, str) else addr_str
        codec_type = codec.get("type", "unknown")
        # Try to form a compatible string
        compat_str = codec_type.lower()
        if compat_str.startswith("wm"):
            compat_str = f"wolfson,{compat_str.lower()}"
        elif compat_str.startswith("cs"):
            compat_str = f"cirrus,{compat_str.lower()}"

        overlay_lines.append("")
        overlay_lines.append("/* TODO: verify I2C instance — defaulting to i2c3 */")
        overlay_lines.append(f"&i2c3 {{")
        overlay_lines.append(f"audio_codec: {compat_str.split(',')[-1]}@{addr_int:x} {{")
        overlay_lines.append(f'\tcompatible = "{compat_str}";')
        overlay_lines.append(f"\treg = <0x{addr_int:02x}>;")
        overlay_lines.append(f"\t#sound-dai-cells = <0>;")
        overlay_lines.append(f'\tstatus = "okay";')
        overlay_lines.append(f"}};")
        overlay_lines.append(f"}};")

    # Display
    display = data.get("display", {})
    if display.get("width") and display.get("height"):
        overlay_lines.append("")
        overlay_lines.append(f"/* Display: {display['width']}x{display['height']} */")
        overlay_lines.append(f"/* TODO: Add display panel node with appropriate compatible */")

    # Audio I2S scaffold
    if data.get("audio", {}).get("i2s"):
        overlay_lines.append("")
        overlay_lines.append("/* TODO: SAI/I2S peripheral config */")

    overlay_lines.append("")
    overlay_lines.append(AUTO_END_C)
    _write_file(overlay_path, "\n".join(overlay_lines) + "\n", force=force)
    print(f"  Synced: {os.path.relpath(overlay_path, ove_dir())}")


def _sync_nuttx(board_yaml, board_dir, force=False):
    """Generate NuttX defconfig fragment from board.yaml."""
    data = board_yaml.data
    board_name = data["board"]["name"]

    nuttx_dir = os.path.join(board_dir, "nuttx")
    if not os.path.isdir(nuttx_dir):
        print(f"  Skipping NuttX sync: {nuttx_dir} does not exist")
        return

    defconfig_path = os.path.join(nuttx_dir, "ove_board_defconfig")
    lines = [AUTO_BEGIN]

    # Serial console baud
    serial = data.get("serial", {}).get("console", {})
    baud = serial.get("baud")
    if baud:
        lines.append(f"CONFIG_USART1_BAUD={baud}")

    # LEDs
    if data.get("leds"):
        lines.append("CONFIG_USERLED=y")
        lines.append("CONFIG_USERLED_LOWER=y")

    # SD card
    if data.get("sdcard"):
        lines.append("CONFIG_MMCSD=y")

    # Watchdog
    if data.get("watchdog"):
        lines.append("CONFIG_WATCHDOG=y")

    # Display
    display = data.get("display", {})
    if display.get("width") and display.get("height"):
        lines.append(f"CONFIG_LCD_MAXWIDTH={display['width']}")
        lines.append(f"CONFIG_LCD_MAXHEIGHT={display['height']}")

    lines.append(AUTO_END)
    _write_file(defconfig_path, "\n".join(lines) + "\n", force=force)
    print(f"  Synced: {os.path.relpath(defconfig_path, ove_dir())}")


def _write_file(path, content, force=False):
    """Write content — force overwrites entirely, default uses marker-based merge."""
    if force:
        dirname = os.path.dirname(path)
        if dirname:
            os.makedirs(dirname, exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
        return
    _write_with_markers(path, content)


def _write_with_markers(path, content):
    """Write content with auto-generation markers.

    If file exists and has markers, replace only the marked region.
    If file exists without markers, prepend content.
    If file does not exist, create it.
    """
    # Detect which marker style is used in the content
    if AUTO_BEGIN_C in content:
        begin_marker = AUTO_BEGIN_C
        end_marker = AUTO_END_C
    else:
        begin_marker = AUTO_BEGIN
        end_marker = AUTO_END

    if os.path.isfile(path):
        with open(path, "r") as f:
            existing = f.read()
        begin_idx = existing.find(begin_marker)
        end_idx = existing.find(end_marker, begin_idx) if begin_idx >= 0 else -1
        if begin_idx >= 0 and end_idx >= 0:
            # Replace between markers
            before = existing[:begin_idx]
            after = existing[end_idx + len(end_marker):]
            merged = before + content + after
            with open(path, "w") as f:
                f.write(merged)
            return
        # File exists but no markers — prepend
        with open(path, "w") as f:
            f.write(content + "\n" + existing)
        return

    dirname = os.path.dirname(path)
    if dirname:
        os.makedirs(dirname, exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


# ---------------------------------------------------------------------------
# Conflict resolution
# ---------------------------------------------------------------------------

def _resolve_conflict(existing_yaml_path, new_data, args):
    """Handle conflict when board.yaml already exists.

    Returns the BoardYaml to save (or None to skip).
    """
    existing = BoardYaml.load(existing_yaml_path)
    new_board = BoardYaml(data=new_data)

    non_interactive = getattr(args, "non_interactive", False)
    overwrite = getattr(args, "overwrite", False)

    if non_interactive:
        if overwrite:
            print("  Overwriting existing board.yaml (--overwrite)")
            return new_board
        else:
            print("  Keeping existing board.yaml (non-interactive, use --overwrite to replace)")
            existing.merge_from(new_board)
            return existing

    # Interactive prompt
    print(f"\n  board.yaml already exists at: {existing_yaml_path}")
    print("  Options:")
    print("    [k] Keep existing (default)")
    print("    [o] Overwrite with new import")
    print("    [m] Merge (keep existing sections, fill missing)")
    print("    [d] Show diff")

    while True:
        try:
            choice = input("  Choice [k/o/m/d]: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            choice = "k"

        if choice in ("", "k"):
            print("  Keeping existing board.yaml")
            return existing
        elif choice == "o":
            print("  Overwriting with new import")
            return new_board
        elif choice == "m":
            print("  Merging: keeping existing sections, filling missing")
            existing.merge_from(new_board)
            return existing
        elif choice == "d":
            _show_diff(existing.data, new_data)
        else:
            print("  Invalid choice. Use k, o, m, or d.")


def _show_diff(old_data, new_data):
    """Print a simple section-level diff."""
    all_keys = sorted(set(list(old_data.keys()) + list(new_data.keys())))
    for key in all_keys:
        if key == "_meta":
            continue
        if key in old_data and key not in new_data:
            print(f"    - {key}: (only in existing)")
        elif key not in old_data and key in new_data:
            print(f"    + {key}: (only in new)")
        elif old_data[key] != new_data[key]:
            print(f"    ~ {key}: differs")
        else:
            print(f"      {key}: same")


# ---------------------------------------------------------------------------
# Post-import registration hooks
# ---------------------------------------------------------------------------

def _register_kconfig(ove_name, board_yaml_data):
    """Auto-register a board in Config.in.hardware (idempotent)."""
    kconfig_path = os.path.join(ove_dir(), "config", "Config.in.hardware")
    if not os.path.isfile(kconfig_path):
        print(f"  Warning: {kconfig_path} not found, skipping Kconfig registration")
        return

    board = board_yaml_data.get("board", {})
    memory = board_yaml_data.get("memory", {})
    clock = board_yaml_data.get("clock", {})

    # Derive Kconfig symbol: OVE_BOARD_ + name uppercased with - → _
    symbol = "OVE_BOARD_" + ove_name.upper().replace("-", "_")

    with open(kconfig_path, "r") as f:
        lines = f.readlines()

    # Check if symbol already exists or board name already mapped
    for line in lines:
        if line.strip().startswith(f"config {symbol}"):
            print(f"  Kconfig: {symbol} already registered, skipping")
            return
        if f'default "{ove_name}"' in line:
            print(f"  Kconfig: {ove_name} already mapped in defaults, skipping")
            return

    mcu_family = board.get("mcu_family", "unknown")
    mcu = board.get("mcu", "unknown")
    flash_kb = memory.get("flash_kb", 0)
    ram_kb = memory.get("ram_kb", 0)
    sysclk = clock.get("sysclk_mhz", "")

    flash_bytes = flash_kb * 1024
    ram_bytes = ram_kb * 1024

    # Build the choice entry block (two-line help matching existing style)
    pretty_name = ove_name.upper()
    help_line1 = f"{pretty_name} board ({mcu_family.upper()} family)."
    spec_parts = []
    if sysclk:
        spec_parts.append(f"@ {sysclk} MHz")
    if flash_kb:
        if flash_kb >= 1024:
            spec_parts.append(f"{flash_kb // 1024} MB Flash")
        else:
            spec_parts.append(f"{flash_kb} KB Flash")
    if ram_kb:
        if ram_kb >= 1024:
            spec_parts.append(f"{ram_kb // 1024} MB RAM")
        else:
            spec_parts.append(f"{ram_kb} KB RAM")
    help_line2 = f"MCU {mcu}" + (", " + ", ".join(spec_parts) if spec_parts else "") + "."

    choice_entry = (
        f"\nconfig {symbol}\n"
        f'    bool "{pretty_name}"\n'
        f"    help\n"
        f"      {help_line1}\n"
        f"      {help_line2}\n"
    )

    # Insert choice entry before 'endchoice'
    # Insert defaults after last default in each section
    new_lines = []
    in_section = None  # track which config section we're in
    for i, line in enumerate(lines):
        stripped = line.rstrip()

        # Insert choice block before endchoice
        if stripped == "endchoice":
            new_lines.append(choice_entry)
            new_lines.append(line)
            continue

        # Track which config section we're in
        if stripped.startswith("config OVE_BOARD_NAME"):
            in_section = "BOARD_NAME"
        elif stripped.startswith("config OVE_FLASH_SIZE"):
            in_section = "FLASH_SIZE"
        elif stripped.startswith("config OVE_RAM_SIZE"):
            in_section = "RAM_SIZE"
        elif stripped.startswith("config OVE_MCU"):
            in_section = "MCU"
        elif stripped.startswith("config ") or stripped.startswith("endmenu"):
            in_section = None

        new_lines.append(line)

        # After the last 'default ...' in each section, insert our default
        if in_section and stripped.strip().startswith("default "):
            # Peek ahead: if the next non-empty line is NOT a default, insert ours
            next_is_default = False
            for j in range(i + 1, len(lines)):
                next_stripped = lines[j].strip()
                if not next_stripped:
                    continue
                if next_stripped.startswith("default "):
                    next_is_default = True
                break
            if not next_is_default:
                if in_section == "BOARD_NAME":
                    new_lines.append(
                        f'    default "{ove_name}" if {symbol}\n'
                    )
                elif in_section == "FLASH_SIZE":
                    new_lines.append(
                        f"    default {flash_bytes} if {symbol}\n"
                    )
                elif in_section == "RAM_SIZE":
                    new_lines.append(
                        f"    default {ram_bytes} if {symbol}\n"
                    )
                elif in_section == "MCU":
                    new_lines.append(
                        f'    default "{mcu}" if {symbol}\n'
                    )

    with open(kconfig_path, "w") as f:
        f.writelines(new_lines)
    print(f"  Kconfig: registered {symbol}")


def _register_constants(ove_name, board_yaml_data, rtos):
    """Auto-register RTOS board mapping in constants.py (idempotent)."""
    constants_path = os.path.join(
        ove_dir(), "config", "ove-cli", "ove", "constants.py"
    )
    if not os.path.isfile(constants_path):
        print(f"  Warning: {constants_path} not found, skipping constants registration")
        return

    meta = board_yaml_data.get("_meta", {})

    with open(constants_path, "r") as f:
        content = f.read()

    if rtos == "nuttx":
        nuttx_board = meta.get("nuttx_board", "")
        nuttx_config = meta.get("nuttx_config", "nsh")
        if not nuttx_board:
            print("  Constants: no nuttx_board in _meta, skipping NuttX mapping")
            return
        entry = f'    "{ove_name}": "{nuttx_board}:{nuttx_config}",'
        dict_name = "NUTTX_BOARD_CONFIGS"
    elif rtos == "zephyr":
        zephyr_board = meta.get("zephyr_board", "")
        if not zephyr_board:
            print("  Constants: no zephyr_board in _meta, skipping Zephyr mapping")
            return
        entry = f'    "{ove_name}": "{zephyr_board}",'
        dict_name = "ZEPHYR_BOARD_MAPPINGS"
    else:
        return

    # Check if already present
    if f'"{ove_name}"' in content and dict_name in content:
        # More precise check: is it in the right dict?
        in_dict = False
        for line in content.splitlines():
            if dict_name in line:
                in_dict = True
            if in_dict and f'"{ove_name}"' in line:
                print(f"  Constants: {ove_name} already in {dict_name}, skipping")
                return
            if in_dict and line.strip() == "}":
                in_dict = False

    # Find closing } of the target dict and insert before it
    lines = content.splitlines(True)
    new_lines = []
    in_target_dict = False
    inserted = False
    for line in lines:
        if dict_name in line and "=" in line:
            in_target_dict = True
        if in_target_dict and not inserted and line.strip() == "}":
            new_lines.append(entry + "\n")
            inserted = True
            in_target_dict = False
        new_lines.append(line)

    if inserted:
        with open(constants_path, "w") as f:
            f.writelines(new_lines)
        print(f"  Constants: registered {ove_name} in {dict_name}")
    else:
        print(f"  Warning: could not find {dict_name} closing brace in constants.py")


def _generate_defconfig(ove_name, board_yaml_data, rtos):
    """Auto-generate a minimal example defconfig for the board."""
    board = board_yaml_data.get("board", {})
    mcu = board.get("mcu", "")

    # Derive short name: STM32F429xx → stm32f429, NRF52840 → nrf52840
    short = mcu.lower().rstrip("x") if mcu else ove_name.split("-")[0]

    defconfig_dir = os.path.join(ove_dir(), "defconfigs", short)
    defconfig_name = f"{short}_{rtos}_example_c_defconfig"
    defconfig_path = os.path.join(defconfig_dir, defconfig_name)

    if os.path.isfile(defconfig_path):
        print(f"  Defconfig: {defconfig_name} already exists, skipping")
        return

    # Kconfig symbol for the board
    symbol = "OVE_BOARD_" + ove_name.upper().replace("-", "_")

    lines = [
        "CONFIG_OVE_APP_EXAMPLE_C=y",
        "CONFIG_OVE_APP_LANG_C=y",
        f"CONFIG_OVE_RTOS_{rtos.upper()}=y",
        f"CONFIG_{symbol}=y",
        "CONFIG_OVE_SYNC=y",
        "# CONFIG_OVE_AUDIO is not set",
        "# CONFIG_OVE_FS is not set",
        "CONFIG_OVE_CONSOLE=y",
        "CONFIG_OVE_LOG=y",
        "CONFIG_OVE_TIME=y",
        "CONFIG_OVE_BSP=y",
        "# CONFIG_OVE_LVGL is not set",
        "CONFIG_OVE_QUEUE=y",
        "CONFIG_OVE_TIMER=y",
        "CONFIG_OVE_EVENTGROUP=y",
        "# CONFIG_OVE_SHELL is not set",
        "# CONFIG_OVE_NVS is not set",
        "# CONFIG_OVE_WATCHDOG is not set",
        "# CONFIG_OVE_WORKQUEUE is not set",
        "# CONFIG_OVE_STREAM is not set",
        "CONFIG_OVE_LOG_LEVEL_INF=y",
    ]

    if rtos == "nuttx":
        lines.append("CONFIG_NUTTX_SOURCE_GIT=y")

    if rtos == "zephyr":
        # Disable Zephyr subsystems not supported by this board
        if "sdcard" not in board_yaml_data:
            lines.append("# CONFIG_ZEPHYR_SD_FILESYSTEM is not set")

    lines.append("CONFIG_OVE_TOOLCHAIN_DOWNLOAD=y")

    os.makedirs(defconfig_dir, exist_ok=True)
    with open(defconfig_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Defconfig: created {os.path.relpath(defconfig_path, ove_dir())}")


def _generate_flash_scripts(board_dir, rtos, mcu_family, ove_name,
                            mcu=""):
    """Auto-generate flash.sh, debug.sh, and gdb.sh for the board."""
    rtos_dir = os.path.join(board_dir, rtos)
    if not os.path.isdir(rtos_dir):
        return

    # Discover OpenOCD board config
    openocd_scripts = "/usr/share/openocd/scripts/board"
    openocd_cfg = None

    # Derive chip prefix for precise matching: STM32F429xx → stm32f429
    chip_prefix = mcu.lower().rstrip("x") if mcu else ""

    if os.path.isdir(openocd_scripts):
        board_files = sorted(os.listdir(openocd_scripts))

        # Strategy 1: match by chip prefix (most specific)
        if chip_prefix:
            for f in board_files:
                if chip_prefix in f and f.endswith(".cfg"):
                    openocd_cfg = f"board/{f}"
                    break

        # Strategy 2: match by mcu_family + "discovery"
        if not openocd_cfg:
            candidate = f"{mcu_family}discovery.cfg"
            if os.path.isfile(os.path.join(openocd_scripts, candidate)):
                openocd_cfg = f"board/{candidate}"

    # Strategy 3: fallback
    if not openocd_cfg:
        openocd_cfg = f"board/{mcu_family}discovery.cfg"

    pretty_name = ove_name.upper()

    scripts = {
        "flash.sh": (
            f"#!/bin/bash\n"
            f"# Flash script for {pretty_name} ({rtos.capitalize()})\n"
            f"# Usage: flash.sh <firmware.elf>\n"
            f"\n"
            f"set -e\n"
            f"\n"
            f'FIRMWARE="${{1:?Usage: $0 <firmware.elf>}}"\n'
            f"\n"
            f'if [ ! -f "$FIRMWARE" ]; then\n'
            f'    echo "Error: firmware file not found: $FIRMWARE"\n'
            f"    exit 1\n"
            f"fi\n"
            f"\n"
            f"openocd \\\n"
            f"    -f {openocd_cfg} \\\n"
            f'    -c "program $FIRMWARE verify reset exit"\n'
        ),
        "debug.sh": (
            f"#!/bin/bash\n"
            f"# Start OpenOCD debug server for {pretty_name} ({rtos.capitalize()})\n"
            f"# Usage: debug.sh\n"
            f"\n"
            f"set -e\n"
            f"\n"
            f"openocd -f {openocd_cfg}\n"
        ),
        "gdb.sh": (
            f"#!/bin/bash\n"
            f"# Connect GDB to OpenOCD for {pretty_name} ({rtos.capitalize()})\n"
            f"# Usage: gdb.sh <firmware.elf>\n"
            f"\n"
            f"set -e\n"
            f"\n"
            f'FIRMWARE="${{1:?Usage: $0 <firmware.elf>}}"\n'
            f"\n"
            f'if [ ! -f "$FIRMWARE" ]; then\n'
            f'    echo "Error: firmware file not found: $FIRMWARE"\n'
            f"    exit 1\n"
            f"fi\n"
            f"\n"
            f'arm-none-eabi-gdb "$FIRMWARE" \\\n'
            f'    -ex "target extended-remote :3333" \\\n'
            f'    -ex "monitor reset halt" \\\n'
            f'    -ex "load"\n'
        ),
    }

    for name, content in scripts.items():
        script_path = os.path.join(rtos_dir, name)
        if os.path.isfile(script_path):
            print(f"  Scripts: {name} already exists, skipping")
            continue
        with open(script_path, "w") as f:
            f.write(content)
        os.chmod(script_path, 0o755)
        print(f"  Scripts: created {os.path.relpath(script_path, ove_dir())}")


def _post_import_register(ove_name, board_yaml_data, rtos):
    """Run all post-import registration hooks."""
    print(f"\n--- Post-import registration for {ove_name} ({rtos}) ---")
    _register_kconfig(ove_name, board_yaml_data)
    _register_constants(ove_name, board_yaml_data, rtos)
    _generate_defconfig(ove_name, board_yaml_data, rtos)
    board_dir = os.path.join(boards_dir(), ove_name)
    board = board_yaml_data.get("board", {})
    mcu_family = board.get("mcu_family", "unknown")
    mcu = board.get("mcu", "")
    _generate_flash_scripts(board_dir, rtos, mcu_family, ove_name, mcu=mcu)
    print("--- Registration complete ---\n")


# ---------------------------------------------------------------------------
# Subcommand: import
# ---------------------------------------------------------------------------

def cmd_import(args):
    rtos = args.import_rtos

    if rtos == "zephyr":
        _import_zephyr(args)
    elif rtos == "nuttx":
        _import_nuttx(args)
    else:
        print(f"Error: unsupported RTOS '{rtos}' for import")
        sys.exit(1)


def _import_zephyr(args):
    zephyr_base = args.zephyr_base or os.path.join(dl_dir(), "zephyr-workspace", "zephyr")
    board_name = args.board

    if not os.path.isdir(zephyr_base):
        print(f"Error: Zephyr base not found: {zephyr_base}")
        print("  Download Zephyr first or specify --zephyr-base")
        sys.exit(1)

    board_dir = _find_zephyr_board_dir(zephyr_base, board_name)
    if not board_dir:
        print(f"Error: Zephyr board '{board_name}' not found in {zephyr_base}/boards/")
        sys.exit(1)

    print(f"Importing Zephyr board: {board_name}")
    print(f"  Source: {board_dir}")

    # Parse DTS
    dts_text = _read_dts_files(board_dir, board_name)
    if not dts_text:
        print(f"  Warning: no DTS files found in {board_dir}")
        data = {"board": {"name": board_name.replace("_", "-"), "mcu_family": "unknown", "mcu": "unknown"}}
        warnings = ["No DTS files found — board.yaml will be minimal"]
    else:
        tree = DtsParser(dts_text).parse()
        data, warnings = _extract_board_yaml_from_dts(tree, board_name)

    # oveRTOS board name
    ove_name = args.ove_name or data["board"]["name"]
    data["board"]["name"] = ove_name

    # Add provenance
    data["_meta"] = {
        "imported_from": "zephyr",
        "import_date": datetime.date.today().isoformat(),
        "zephyr_board": board_name,
    }

    # Target directory
    target_dir = os.path.join(boards_dir(), ove_name)

    # Check for existing board.yaml
    yaml_path = os.path.join(target_dir, "board.yaml")
    if os.path.isfile(yaml_path):
        board_yaml = _resolve_conflict(yaml_path, data, args)
        if board_yaml is None:
            return
    else:
        board_yaml = BoardYaml(data=data)

    # Validate (strip _meta)
    board_yaml.validate()

    # Save board.yaml
    os.makedirs(target_dir, exist_ok=True)
    board_yaml.save(yaml_path)
    print(f"  Saved: {os.path.relpath(yaml_path, ove_dir())}")

    # Create Zephyr scaffold
    zephyr_board_name = board_name  # keep original Zephyr name for .conf/.overlay
    zephyr_scaffold_dir = os.path.join(target_dir, "zephyr")
    _render_scaffold(
        "zephyr",
        ove_name,
        data["board"]["mcu_family"],
        data["board"]["mcu"],
        zephyr_scaffold_dir,
    )

    # Create boards/ subdirectory with empty .conf and .overlay
    zephyr_boards_dir = os.path.join(zephyr_scaffold_dir, "boards")
    os.makedirs(zephyr_boards_dir, exist_ok=True)
    for ext in [".conf", ".overlay"]:
        fpath = os.path.join(zephyr_boards_dir, f"{zephyr_board_name}{ext}")
        if not os.path.isfile(fpath):
            with open(fpath, "w") as f:
                if ext == ".conf":
                    f.write(f"{AUTO_BEGIN}\n{AUTO_END}\n")
                else:
                    f.write(f"{AUTO_BEGIN_C}\n{AUTO_END_C}\n")
            print(f"  Created: {os.path.relpath(fpath, ove_dir())}")

    # Post-import registration — use saved board.yaml data (may differ from
    # extracted data if user kept existing), but merge in new _meta so RTOS
    # mapping info (zephyr_board) is available for constants registration.
    reg_data = board_yaml.data
    reg_data.setdefault("_meta", {}).update(data.get("_meta", {}))
    _post_import_register(ove_name, reg_data, "zephyr")

    # Print warnings
    if warnings:
        print("\n  Fields that need manual review:")
        for w in warnings:
            print(f"    - {w}")

    print(f"\nImport complete: boards/{ove_name}/")


def _import_nuttx(args):
    nuttx_base = args.nuttx_base or os.path.join(dl_dir(), "nuttx")
    board_name = args.board
    config_variant = args.config or "nsh"

    if not os.path.isdir(nuttx_base):
        print(f"Error: NuttX base not found: {nuttx_base}")
        print("  Download NuttX first or specify --nuttx-base")
        sys.exit(1)

    board_dir = _find_nuttx_board_dir(nuttx_base, board_name)
    if not board_dir:
        print(f"Error: NuttX board '{board_name}' not found in {nuttx_base}/boards/")
        sys.exit(1)

    print(f"Importing NuttX board: {board_name} (config: {config_variant})")
    print(f"  Source: {board_dir}")

    data, warnings = _extract_board_yaml_from_nuttx(board_dir, config_variant, board_name)

    # oveRTOS board name
    ove_name = args.ove_name or data["board"]["name"]
    data["board"]["name"] = ove_name

    # Add provenance
    data["_meta"] = {
        "imported_from": "nuttx",
        "import_date": datetime.date.today().isoformat(),
        "nuttx_board": board_name,
        "nuttx_config": config_variant,
    }

    # Target directory
    target_dir = os.path.join(boards_dir(), ove_name)

    # Check for existing board.yaml
    yaml_path = os.path.join(target_dir, "board.yaml")
    if os.path.isfile(yaml_path):
        board_yaml = _resolve_conflict(yaml_path, data, args)
        if board_yaml is None:
            return
    else:
        board_yaml = BoardYaml(data=data)

    # Validate
    board_yaml.validate()

    # Save board.yaml
    os.makedirs(target_dir, exist_ok=True)
    board_yaml.save(yaml_path)
    print(f"  Saved: {os.path.relpath(yaml_path, ove_dir())}")

    # Create NuttX scaffold
    nuttx_scaffold_dir = os.path.join(target_dir, "nuttx")
    _render_scaffold(
        "nuttx",
        ove_name,
        data["board"]["mcu_family"],
        data["board"]["mcu"],
        nuttx_scaffold_dir,
    )

    # Post-import registration — use saved board.yaml data with merged _meta
    reg_data = board_yaml.data
    reg_data.setdefault("_meta", {}).update(data.get("_meta", {}))
    _post_import_register(ove_name, reg_data, "nuttx")

    # Print warnings
    if warnings:
        print("\n  Fields that need manual review:")
        for w in warnings:
            print(f"    - {w}")

    print(f"\nImport complete: boards/{ove_name}/")


# ---------------------------------------------------------------------------
# Subcommand: register
# ---------------------------------------------------------------------------

def cmd_register(args):
    """Re-run post-import registration on an existing board."""
    board_name = args.board
    board_path = os.path.join(boards_dir(), board_name)
    yaml_path = os.path.join(board_path, "board.yaml")

    if not os.path.isfile(yaml_path):
        print(f"Error: board.yaml not found: {yaml_path}")
        sys.exit(1)

    board_yaml = BoardYaml.load(yaml_path)
    board_yaml.validate()
    data = board_yaml.data

    # Register for each RTOS subdirectory present
    registered = False
    for rtos in ["nuttx", "zephyr"]:
        if os.path.isdir(os.path.join(board_path, rtos)):
            _post_import_register(board_name, data, rtos)
            registered = True

    if not registered:
        print(f"No RTOS subdirectories found in {board_path}/")
        print("  Expected: nuttx/ or zephyr/")


# ---------------------------------------------------------------------------
# Subcommand: sync
# ---------------------------------------------------------------------------

def cmd_sync(args):
    board_name = args.board
    rtos_filter = args.rtos or "all"

    board_dir = os.path.join(boards_dir(), board_name)
    yaml_path = os.path.join(board_dir, "board.yaml")

    if not os.path.isfile(yaml_path):
        print(f"Error: board.yaml not found: {yaml_path}")
        sys.exit(1)

    board_yaml = BoardYaml.load(yaml_path)
    board_yaml.validate()

    force = getattr(args, "force", False)

    print(f"Syncing board: {board_name}")

    if rtos_filter in ("zephyr", "all"):
        _sync_zephyr(board_yaml, board_dir, force=force)
    if rtos_filter in ("nuttx", "all"):
        _sync_nuttx(board_yaml, board_dir, force=force)

    print("Sync complete.")


# ---------------------------------------------------------------------------
# Subcommand: list
# ---------------------------------------------------------------------------

def cmd_list(args):
    bdir = boards_dir()
    if not os.path.isdir(bdir):
        print("No boards directory found.")
        return

    rows = []
    for entry in sorted(os.listdir(bdir)):
        board_path = os.path.join(bdir, entry)
        if not os.path.isdir(board_path):
            continue
        yaml_path = os.path.join(board_path, "board.yaml")
        if not os.path.isfile(yaml_path):
            continue
        board_yaml = BoardYaml.load(yaml_path)
        bd = board_yaml.data.get("board", {})
        name = bd.get("name", entry)
        mcu = bd.get("mcu", "")
        family = bd.get("mcu_family", "")

        # Detect RTOS subdirectories
        rtos_list = []
        for rtos in ["freertos", "zephyr", "nuttx", "posix"]:
            if os.path.isdir(os.path.join(board_path, rtos)):
                rtos_list.append(rtos)

        rows.append((name, family, mcu, ", ".join(rtos_list) or "-"))

    if not rows:
        print("No boards found.")
        return

    # Print table
    headers = ("Board", "MCU Family", "MCU", "RTOS Support")
    widths = [max(len(h), max(len(r[i]) for r in rows)) for i, h in enumerate(headers)]
    fmt = "  ".join(f"{{:<{w}}}" for w in widths)

    print(fmt.format(*headers))
    print(fmt.format(*("-" * w for w in widths)))
    for row in rows:
        print(fmt.format(*row))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="oveRTOS Board Import & Sync Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            examples:
              %(prog)s import zephyr --board stm32f746g_disco
              %(prog)s import nuttx  --board stm32f746g-disco --config nsh
              %(prog)s sync   --board stm32f746g-discovery --rtos all
              %(prog)s list
        """),
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # --- import ---
    import_parser = subparsers.add_parser("import", help="Import board from RTOS source tree")
    import_sub = import_parser.add_subparsers(dest="import_rtos", required=True)

    # import zephyr
    zephyr_parser = import_sub.add_parser("zephyr", help="Import from Zephyr board definition")
    zephyr_parser.add_argument("--board", required=True, help="Zephyr board name (e.g. stm32f746g_disco)")
    zephyr_parser.add_argument("--zephyr-base", help="Path to Zephyr source tree")
    zephyr_parser.add_argument("--ove-name", help="Override oveRTOS board name")
    zephyr_parser.add_argument("--non-interactive", action="store_true", help="Non-interactive mode")
    zephyr_parser.add_argument("--overwrite", action="store_true", help="Overwrite existing board.yaml")
    zephyr_parser.set_defaults(func=cmd_import)

    # import nuttx
    nuttx_parser = import_sub.add_parser("nuttx", help="Import from NuttX board definition")
    nuttx_parser.add_argument("--board", required=True, help="NuttX board name (e.g. stm32f746g-disco)")
    nuttx_parser.add_argument("--nuttx-base", help="Path to NuttX source tree")
    nuttx_parser.add_argument("--config", help="NuttX config variant (default: nsh)")
    nuttx_parser.add_argument("--ove-name", help="Override oveRTOS board name")
    nuttx_parser.add_argument("--non-interactive", action="store_true", help="Non-interactive mode")
    nuttx_parser.add_argument("--overwrite", action="store_true", help="Overwrite existing board.yaml")
    nuttx_parser.set_defaults(func=cmd_import)

    # --- sync ---
    sync_parser = subparsers.add_parser("sync", help="Sync board.yaml to RTOS configs")
    sync_parser.add_argument("--board", required=True, help="oveRTOS board name")
    sync_parser.add_argument("--rtos", choices=["zephyr", "nuttx", "all"], default="all",
                             help="Target RTOS (default: all)")
    sync_parser.add_argument("--merge", action="store_true",
                             help="Replace only auto-generated sections")
    sync_parser.add_argument("--force", action="store_true",
                             help="Overwrite files entirely")
    sync_parser.set_defaults(func=cmd_sync)

    # --- register ---
    register_parser = subparsers.add_parser(
        "register", help="Re-run post-import registration on existing board"
    )
    register_parser.add_argument("--board", required=True, help="oveRTOS board name")
    register_parser.set_defaults(func=cmd_register)

    # --- list ---
    list_parser = subparsers.add_parser("list", help="List all oveRTOS boards")
    list_parser.set_defaults(func=cmd_list)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
