#!/usr/bin/env python3

# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""Generate board_desc.h from a board YAML descriptor.

Usage:
    gen_board_desc.py --board-yaml boards/stm32f746g-discovery/board.yaml \
                      --output output/generated/board_desc.h
"""

import argparse
import json
import os
import sys

try:
    import yaml
except ImportError:
    print("Error: pyyaml not installed. Install with: pip install pyyaml")
    sys.exit(1)

try:
    import jsonschema
except ImportError:
    print("Error: jsonschema not installed. Install with: pip install jsonschema")
    sys.exit(1)


def load_yaml(path):
    with open(path, "r") as f:
        return yaml.safe_load(f)


def load_schema(ove_dir):
    schema_path = os.path.join(ove_dir, "config", "schemas", "board_schema.json")
    with open(schema_path, "r") as f:
        return json.load(f)


def validate(board, schema):
    try:
        jsonschema.validate(instance=board, schema=schema)
    except jsonschema.ValidationError as e:
        print(f"Board YAML validation error: {e.message}")
        sys.exit(1)


def c_str(s):
    """Escape a string for use in a C string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def hex_or_int(val):
    """Return an integer from a string that may be hex (0x...) or decimal."""
    if isinstance(val, int):
        return val
    return int(val, 0)


def generate_header(board):
    """Generate board_desc.h content from parsed board YAML."""
    lines = []
    lines.append("/*")
    lines.append(" * Auto-generated by gen_board_desc.py — do not edit.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef OVE_BOARD_DESC_H")
    lines.append("#define OVE_BOARD_DESC_H")
    lines.append("")

    # --- Board identity ---
    b = board["board"]
    lines.append("/* Board identity */")
    lines.append(f'#define OVE_BOARD_NAME       "{c_str(b["name"])}"')
    lines.append(f'#define OVE_BOARD_MCU_FAMILY "{c_str(b["mcu_family"])}"')
    lines.append(f'#define OVE_BOARD_MCU        "{c_str(b["mcu"])}"')
    lines.append("")

    # --- Clock ---
    if "clock" in board:
        clk = board["clock"]
        lines.append("/* Clock configuration */")
        for key in ["hse_freq_mhz", "sysclk_mhz", "ahb_div", "apb1_div", "apb2_div"]:
            if key in clk:
                lines.append(f"#define OVE_CLOCK_{key.upper()} {clk[key]}")
        lines.append("")

    # --- Memory ---
    if "memory" in board:
        mem = board["memory"]
        lines.append("/* Memory layout */")
        for key in ["flash_kb", "ram_kb", "dtcm_kb", "sdram_kb"]:
            if key in mem:
                lines.append(f"#define OVE_MEMORY_{key.upper()} {mem[key]}")
        if "sdram_start" in mem:
            lines.append(f"#define OVE_MEMORY_SDRAM_START {mem['sdram_start']}")
        lines.append("")

    # --- GPIO ---
    if "gpio" in board:
        gpio = board["gpio"]
        lines.append("/* GPIO configuration */")
        lines.append(f"#define OVE_GPIO_PORT_COUNT    {gpio.get('port_count', 0)}")
        lines.append(f"#define OVE_GPIO_PINS_PER_PORT {gpio.get('pins_per_port', 16)}")
        lines.append("")

    # --- LEDs ---
    if "leds" in board:
        leds = board["leds"]
        lines.append("/* LED configuration */")
        lines.append(f"#define OVE_LED_COUNT {len(leds)}")
        for i, led in enumerate(leds):
            prefix = f"OVE_LED{i}"
            lines.append(f"#define {prefix}_PORT       {led['port']}")
            lines.append(f"#define {prefix}_PIN        {led['pin']}")
            active_low = 1 if led.get("active_low", False) else 0
            lines.append(f"#define {prefix}_ACTIVE_LOW {active_low}")
        lines.append("")

    # --- Audio ---
    if "audio" in board:
        audio = board["audio"]
        if "i2s" in audio:
            i2s = audio["i2s"]
            lines.append("/* Audio I2S configuration */")
            for key in ["sample_rate", "bit_depth", "channels", "buffer_samples"]:
                if key in i2s:
                    lines.append(f"#define OVE_AUDIO_I2S_{key.upper()} {i2s[key]}")
            lines.append("")
        if "codec" in audio:
            codec = audio["codec"]
            lines.append("/* Audio codec configuration */")
            if "type" in codec:
                lines.append(f'#define OVE_AUDIO_CODEC_TYPE "{c_str(codec["type"])}"')
            if "i2c_addr" in codec:
                lines.append(f"#define OVE_AUDIO_CODEC_I2C_ADDR {codec['i2c_addr']}")
            lines.append("")

    # --- Display ---
    if "display" in board:
        disp = board["display"]
        lines.append("/* Display configuration */")
        if "width" in disp:
            lines.append(f"#define OVE_DISPLAY_WIDTH  {disp['width']}")
        if "height" in disp:
            lines.append(f"#define OVE_DISPLAY_HEIGHT {disp['height']}")
        if "color_format" in disp:
            lines.append(f'#define OVE_DISPLAY_COLOR_FORMAT "{c_str(disp["color_format"])}"')
        lines.append("")

    # --- Serial ---
    if "serial" in board:
        serial = board["serial"]
        if "console" in serial:
            con = serial["console"]
            lines.append("/* Serial console configuration */")
            if "baud" in con:
                lines.append(f"#define OVE_SERIAL_CONSOLE_BAUD {con['baud']}")
            if "tx_pin" in con:
                lines.append(f'#define OVE_SERIAL_CONSOLE_TX_PIN "{c_str(con["tx_pin"])}"')
            if "rx_pin" in con:
                lines.append(f'#define OVE_SERIAL_CONSOLE_RX_PIN "{c_str(con["rx_pin"])}"')
            if "rx_buffer_size" in con:
                lines.append(f"#define OVE_SERIAL_CONSOLE_RX_BUFFER_SIZE {con['rx_buffer_size']}")
            lines.append("")

    # --- SD Card ---
    if "sdcard" in board:
        sd = board["sdcard"]
        lines.append("/* SD card configuration */")
        if "interface" in sd:
            lines.append(f'#define OVE_SDCARD_INTERFACE "{c_str(sd["interface"])}"')
        lines.append("")

    # --- Watchdog ---
    if "watchdog" in board:
        wd = board["watchdog"]
        lines.append("/* Watchdog configuration */")
        if "timeout_ms" in wd:
            lines.append(f"#define OVE_WATCHDOG_TIMEOUT_MS {wd['timeout_ms']}")
        lines.append("")

    # --- Runtime descriptor struct ---
    lines.append("/* Runtime board descriptor */")
    lines.append('#include "ove/board_types.h"')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    # Static LED table
    led_count = len(board.get("leds", []))
    if led_count > 0:
        lines.append(f"static const struct ove_led_desc ove_board_leds[{led_count}] = {{")
        for led in board["leds"]:
            active_low = 1 if led.get("active_low", False) else 0
            lines.append(f"    {{ {led['port']}, {led['pin']}, {active_low} }},")
        lines.append("};")
    else:
        lines.append("#define ove_board_leds ((const struct ove_led_desc *)0)")
    lines.append("")

    gpio_port_count = board.get("gpio", {}).get("port_count", 0)
    gpio_pins_per_port = board.get("gpio", {}).get("pins_per_port", 16)

    lines.append("static const struct ove_board_desc ove_board_descriptor = {")
    lines.append(f'    .name = OVE_BOARD_NAME,')
    lines.append(f'    .mcu_family = OVE_BOARD_MCU_FAMILY,')
    lines.append(f'    .mcu = OVE_BOARD_MCU,')
    lines.append(f"    .gpio_port_count = {gpio_port_count},")
    lines.append(f"    .gpio_pins_per_port = {gpio_pins_per_port},")
    lines.append(f"    .led_count = {led_count},")
    lines.append(f"    .leds = ove_board_leds,")
    lines.append("};")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* OVE_BOARD_DESC_H */")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate board_desc.h from board YAML")
    parser.add_argument("--board-yaml", required=True,
                        help="Path to board.yaml file")
    parser.add_argument("--output", required=True,
                        help="Output path for board_desc.h")
    args = parser.parse_args()

    ove_dir = os.environ.get("OVE_DIR",
        os.path.dirname(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__)))))

    board = load_yaml(args.board_yaml)
    # Strip _meta (added by board_tool.py) before validation
    board_clean = {k: v for k, v in board.items() if k != "_meta"}
    schema = load_schema(ove_dir)
    validate(board_clean, schema)

    header = generate_header(board)

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as f:
        f.write(header)

    print(f"  Generated: {args.output}")


if __name__ == "__main__":
    main()
