lang: zig
config_name: example_zig
description: "Zig Demo"
zig:
  src_dir: src
  lib_name: example_zig
defconfig:
  - CONFIG_OVE_BSP=y
  - CONFIG_OVE_LVGL=y
  - CONFIG_OVE_QUEUE=y
  - CONFIG_OVE_TIMER=y
