lang: cpp
config_name: lvgl_benchmark_cpp_heap
description: "LVGL rendering benchmark (C++)"
sources:
  - ../../../c/heap/lvgl_benchmark/src/benchmark_perf.c
  - ../../../c/heap/lvgl_benchmark/src/assets/benchmark_cogwheel_rgb.c
  - ../../../c/heap/lvgl_benchmark/src/assets/benchmark_cogwheel_argb.c
  - ../../../c/heap/lvgl_benchmark/src/assets/benchmark_avatar.c
  - src/app.cpp
includes:
  - ../../../c/heap/lvgl_benchmark/include
defconfig:
  - CONFIG_OVE_BSP=y
  - CONFIG_OVE_LVGL=y
  - CONFIG_OVE_TIMER=y
