#ifndef OVE_NET_HTTPD_UI_H
#define OVE_NET_HTTPD_UI_H

#include <stddef.h>

static const char httpd_index_html[] =
	"<!DOCTYPE html>"
	"<html lang='en'><head><meta charset='utf-8'>"
	"<meta name='viewport' content='width=device-width,initial-scale=1'>"
	"<title>oveRTOS</title>"
	"<style>"
	"*{box-sizing:border-box;margin:0;padding:0}"
	"body{font-family:-apple-system,'Segoe UI',sans-serif;background:#1a1a2e;"
	"color:#eee;padding:16px;max-width:600px;margin:0 auto}"
	".card{background:#16213e;border-radius:8px;padding:16px;margin-bottom:12px}"
	"h2{font-size:14px;color:#a0a0b0;text-transform:uppercase;"
	"letter-spacing:1px;margin-bottom:8px}"
	".btn{background:#0f3460;border:none;color:#eee;padding:8px 16px;"
	"border-radius:4px;cursor:pointer;font-size:13px}"
	".btn:hover{background:#1a4a8a}"
	".btn.on{background:#27ae60}"
	"input[type=text]{background:#0d1b2a;border:1px solid #2a2a4a;color:#eee;"
	"padding:6px 10px;border-radius:4px;width:100%}"
	"#console{background:#0d1b2a;font-family:monospace;font-size:12px;"
	"padding:8px;border-radius:4px;max-height:200px;overflow-y:auto;"
	"white-space:pre-wrap}"
	".led-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:8px}"
	".dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px}"
	".dot.on{background:#27ae60}.dot.off{background:#555}"
	"table{width:100%;border-collapse:collapse}"
	"th,td{text-align:left;padding:6px 8px;border-bottom:1px solid #2a2a4a}"
	"th{color:#a0a0b0;font-size:12px}"
	".fg{display:flex;gap:8px;margin-bottom:8px}"
	".fg label{font-size:12px;color:#a0a0b0;margin-bottom:2px;display:block}"
	".fg>div{flex:1}"
	".hdr{text-align:center;padding:16px 0 12px}"
	".hdr h1{font-size:20px;font-weight:600}"
	".hdr span{color:#a0a0b0;font-size:12px}"
	"</style></head><body>"
	"<div class='hdr'><h1>&#9889; oveRTOS</h1>"
	"<span>Device Dashboard</span></div>"
	"<div class='card'><h2>System Info</h2>"
	"<div id='info'>Loading...</div></div>"
	"<div class='card'><h2>LEDs</h2>"
	"<div id='leds' class='led-grid'></div></div>"
	"<div class='card'><h2>GPIO</h2>"
	"<table><thead><tr><th>Port</th><th>Pin</th><th>Value</th><th></th></tr></thead>"
	"<tbody id='gpio'></tbody></table></div>"
	"<div class='card'><h2>Network</h2>"
	"<div id='netinfo'></div>"
	"<div class='fg'>"
	"<div><label>IP</label><input type='text' id='n_ip'></div>"
	"<div><label>Gateway</label><input type='text' id='n_gw'></div>"
	"<div><label>DNS</label><input type='text' id='n_dns'></div>"
	"</div>"
	"<button class='btn' onclick='saveNet()'>Save</button></div>"
	"<div class='card'><h2>Console "
	"<button class='btn' onclick='clrLog()' style='float:right;padding:4px 10px;"
	"font-size:11px'>Clear</button></h2>"
	"<div id='console'></div></div>"
	"<script>"
	"async function api(m,p,b){"
	"var o={method:m,headers:{'Content-Type':'application/json'}};"
	"if(b)o.body=JSON.stringify(b);"
	"try{var r=await fetch(p,o);return await r.json()}"
	"catch(e){return null}}"
	"function fmtUp(s){"
	"var h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sc=s%60;"
	"return h+':'+String(m).padStart(2,'0')+':'+String(sc).padStart(2,'0')}"
	"async function loadInfo(){"
	"var d=await api('GET','/api/info');"
	"if(!d)return;"
	"document.getElementById('info').innerHTML="
	"'<b>Board:</b> '+d.board+'<br>'"
	"+'<b>RTOS:</b> '+d.rtos+'<br>'"
	"+'<b>Uptime:</b> '+fmtUp(d.uptime)+'<br>'"
	"+'<b>IP:</b> '+d.ip}"
	"async function loadLeds(){"
	"var d=await api('GET','/api/leds');"
	"if(!d||!d.leds)return;"
	"var h='';d.leds.forEach(function(l){"
	"var c=l.on?'on':'off';"
	"h+='<button class=\"btn '+(l.on?'on':'')+'\" "
	"onclick=\"toggleLed('+l.id+','+l.on+')\">"
	"<span class=\"dot '+c+'\"></span>LED '+l.id+'</button>'});"
	"document.getElementById('leds').innerHTML=h}"
	"async function toggleLed(id,on){"
	"await api('POST','/api/leds/'+id,{on:!on});loadLeds()}"
	"async function readGpio(port,pin){"
	"var d=await api('GET','/api/gpio/'+port+'/'+pin);"
	"if(!d)return;"
	"var el=document.getElementById('gv_'+port+'_'+pin);"
	"if(el)el.textContent=d.value}"
	"function initGpio(){"
	"var h='';for(var i=0;i<4;i++){"
	"h+='<tr><td>0</td><td>'+i+'</td>'"
	"+'<td id=\"gv_0_'+i+'\">-</td>'"
	"+'<td><button class=\"btn\" onclick=\"readGpio(0,'+i+')\">Read</button>'"
	"+'<button class=\"btn\" onclick=\"toggleGpio(0,'+i+')\" "
	"style=\"margin-left:4px\">Toggle</button></td></tr>'}"
	"document.getElementById('gpio').innerHTML=h}"
	"async function toggleGpio(port,pin){"
	"await api('POST','/api/gpio/'+port+'/'+pin,{toggle:true});"
	"readGpio(port,pin)}"
	"async function loadNetwork(){"
	"var d=await api('GET','/api/network');"
	"if(!d)return;"
	"document.getElementById('n_ip').value=d.ip||'';"
	"document.getElementById('n_gw').value=d.gateway||'';"
	"document.getElementById('n_dns').value=d.dns||'';"
	"document.getElementById('netinfo').innerHTML="
	"'<span style=\"font-size:12px;color:#a0a0b0\">"
	"Current: '+d.ip+' / '+d.gateway+' / '+d.dns+'</span><br><br>'}"
	"async function saveNet(){"
	"await api('POST','/api/network',{"
	"ip:document.getElementById('n_ip').value,"
	"gateway:document.getElementById('n_gw').value,"
	"dns:document.getElementById('n_dns').value});"
	"alert('Network settings saved')}"
	"var logBuf='';"
	"async function loadLog(){"
	"var d=await api('GET','/api/log');"
	"if(!d||!d.lines)return;"
	"var el=document.getElementById('console');"
	"logBuf+=d.lines.join('\\n')+'\\n';"
	"el.textContent=logBuf;"
	"el.scrollTop=el.scrollHeight}"
	"function clrLog(){"
	"logBuf='';document.getElementById('console').textContent=''}"
	"loadInfo();loadLeds();initGpio();loadNetwork();loadLog();"
	"setInterval(loadInfo,2000);setInterval(loadLog,1000);"
	"</script></body></html>";

static const size_t httpd_index_html_len = sizeof(httpd_index_html) - 1;

#endif /* OVE_NET_HTTPD_UI_H */
