# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""Configuration generation package.

Split out of the original ``configure.py`` for navigability:

- :mod:`templates`   — Jinja2 rendering of ove_config.h / .cmake / RTOS configs
- :mod:`board_desc`  — board.yaml -> board_desc.h
- :mod:`assets`      — app.yaml + image pipeline -> app_sources.cmake
- :mod:`patches`     — RTOS source patching (legacy; build.py has its own)
"""

import json
import os

from .templates import render_template, generate_configs
from .board_desc import generate_board_desc
from .assets import generate_app_sources
from .patches import apply_patches, apply_all_patches

__all__ = [
    "render_template",
    "generate_configs",
    "generate_board_desc",
    "generate_app_sources",
    "apply_patches",
    "apply_all_patches",
    "configure_all",
    "cmd_configure",
]


def configure_all(ws):
    """Run full configuration: board desc + app sources + template generation."""
    ws.require_config()
    ws.ensure_dirs()
    generate_board_desc(ws)
    generate_app_sources(ws)
    print("=== Generating configuration ===")
    generate_configs(ws)
    _emit_cmake_user_presets(ws)


def _emit_cmake_user_presets(ws):
    """Write a CMakeUserPresets.json at repo root for IDE consumption.

    The preset points at whichever workspace was just configured. IDEs
    (VS Code CMake Tools, CLion) pick this up automatically and can
    configure / build without going through `make` or `ove build`.
    """
    if ws.rtos == "nuttx":
        # NuttX wraps cmake itself; an external preset would just confuse
        # CLion when it tries to invoke without nuttx-cmake's build glue.
        return
    board_dir = ws.board_dir
    if not board_dir:
        return

    binary_dir = os.path.join(ws.build_dir, "firmware")
    cache_vars = {
        "OVE_DIR": ws.ove_dir,
        "OVE_GEN_DIR": ws.gen_dir,
        "OVE_DL_DIR": ws.ws_dl_dir,
        "BOARD_DIR": board_dir,
    }
    if ws.app_dir:
        cache_vars["OVE_APP_DIR"] = ws.app_dir
    if ws.toolchain_dir:
        cache_vars["OVE_TOOLCHAIN_DIR"] = ws.toolchain_dir
    toolchain_file = os.path.join(board_dir, "cmake", "arm-none-eabi.cmake")
    if os.path.isfile(toolchain_file):
        cache_vars["CMAKE_TOOLCHAIN_FILE"] = toolchain_file

    preset_name = (
        f"ove-{ws.board_name or 'unknown'}-{ws.rtos or 'unknown'}"
        f"-{os.path.basename(ws.app_dir) if ws.app_dir else 'noapp'}"
    )
    presets = {
        "version": 6,
        "cmakeMinimumRequired": {
            "major": 3, "minor": 25, "patch": 0,
        },
        "configurePresets": [{
            "name": preset_name,
            "displayName": f"oveRTOS - {preset_name}",
            "description": (
                "Generated by `ove configure`. Re-run after switching "
                "workspace; this file is gitignored."),
            "binaryDir": binary_dir,
            "generator": "Unix Makefiles",
            "cacheVariables": cache_vars,
        }],
        "buildPresets": [{
            "name": preset_name,
            "configurePreset": preset_name,
        }],
    }
    out = os.path.join(ws.ove_dir, "CMakeUserPresets.json")
    with open(out, "w") as f:
        json.dump(presets, f, indent=2)
        f.write("\n")
    print(f"  Generated: {out}")


def cmd_configure(args):
    """CLI entry point for 'ove configure'."""
    import os
    from ..workspace import Workspace
    ws = Workspace()
    if getattr(args, "dry_run", False):
        ws.require_config()
        print(f"[dry-run] would generate config for {ws.rtos}")
        print(f"[dry-run] gen dir:    {ws.gen_dir}")
        targets = ["ove_config.h", "ove_config.cmake"]
        if ws.rtos == "freertos":
            targets.append("FreeRTOSConfig.h")
        elif ws.rtos == "zephyr":
            targets.append("prj.conf")
        elif ws.rtos == "nuttx":
            targets.append("nuttx_defconfig")
        for t in targets:
            print(f"[dry-run]   -> {os.path.join(ws.gen_dir, t)}")
        if ws.app_dir:
            print(f"[dry-run]   -> {os.path.join(ws.gen_dir, 'app_sources.cmake')}")
        if ws.board_dir:
            print(f"[dry-run]   -> {os.path.join(ws.gen_dir, 'board_desc.h')}")
        return
    configure_all(ws)
