# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""Board descriptor (``board.yaml`` -> ``board_desc.h``) generation."""

import json
import os
import sys

try:
    import yaml
except ImportError:
    yaml = None

try:
    import jsonschema
except ImportError:
    jsonschema = None


def _c_str(s):
    """Escape a string for use in a C string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _generate_board_desc_header(board):
    """Generate board_desc.h content from parsed board YAML."""
    lines = []
    lines.append("/*")
    lines.append(" * Auto-generated by gen_board_desc.py -- do not edit.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef OVE_BOARD_DESC_H")
    lines.append("#define OVE_BOARD_DESC_H")
    lines.append("")

    b = board["board"]
    lines.append("/* Board identity */")
    lines.append(f'#define OVE_BOARD_NAME       "{_c_str(b["name"])}"')
    lines.append(f'#define OVE_BOARD_MCU_FAMILY "{_c_str(b["mcu_family"])}"')
    lines.append(f'#define OVE_BOARD_MCU        "{_c_str(b["mcu"])}"')
    lines.append("")

    if "clock" in board:
        clk = board["clock"]
        lines.append("/* Clock configuration */")
        for key in ["hse_freq_mhz", "sysclk_mhz", "ahb_div", "apb1_div",
                     "apb2_div"]:
            if key in clk:
                lines.append(
                    f"#define OVE_CLOCK_{key.upper()} {clk[key]}")
        lines.append("")

    if "memory" in board:
        mem = board["memory"]
        lines.append("/* Memory layout */")
        for key in ["flash_kb", "ram_kb", "dtcm_kb", "sdram_kb"]:
            if key in mem:
                lines.append(
                    f"#define OVE_MEMORY_{key.upper()} {mem[key]}")
        if "sdram_start" in mem:
            lines.append(
                f"#define OVE_MEMORY_SDRAM_START {mem['sdram_start']}")
        lines.append("")

    gpio = board.get("gpio", {})
    lines.append("/* GPIO configuration */")
    lines.append(
        f"#define OVE_GPIO_PORT_COUNT    "
        f"{gpio.get('port_count', 0)}")
    lines.append(
        f"#define OVE_GPIO_PINS_PER_PORT "
        f"{gpio.get('pins_per_port', 16)}")
    lines.append("")

    if "leds" in board:
        leds = board["leds"]
        lines.append("/* LED configuration */")
        lines.append(f"#define OVE_LED_COUNT {len(leds)}")
        for i, led in enumerate(leds):
            prefix = f"OVE_LED{i}"
            lines.append(f"#define {prefix}_PORT       {led['port']}")
            lines.append(f"#define {prefix}_PIN        {led['pin']}")
            active_low = 1 if led.get("active_low", False) else 0
            lines.append(f"#define {prefix}_ACTIVE_LOW {active_low}")
        lines.append("")

    if "audio" in board:
        audio = board["audio"]
        if "i2s" in audio:
            i2s = audio["i2s"]
            lines.append("/* Audio I2S configuration */")
            for key in ["sample_rate", "bit_depth", "channels",
                        "buffer_samples"]:
                if key in i2s:
                    lines.append(
                        f"#define OVE_AUDIO_I2S_{key.upper()} "
                        f"{i2s[key]}")
            lines.append("")
        if "codec" in audio:
            codec = audio["codec"]
            lines.append("/* Audio codec configuration */")
            if "type" in codec:
                lines.append(
                    f'#define OVE_AUDIO_CODEC_TYPE '
                    f'"{_c_str(codec["type"])}"')
            if "i2c_addr" in codec:
                lines.append(
                    f"#define OVE_AUDIO_CODEC_I2C_ADDR "
                    f"{codec['i2c_addr']}")
            lines.append("")

    if "display" in board:
        disp = board["display"]
        lines.append("/* Display configuration */")
        if "width" in disp:
            lines.append(f"#define OVE_DISPLAY_WIDTH  {disp['width']}")
        if "height" in disp:
            lines.append(f"#define OVE_DISPLAY_HEIGHT {disp['height']}")
        if "color_format" in disp:
            lines.append(
                f'#define OVE_DISPLAY_COLOR_FORMAT '
                f'"{_c_str(disp["color_format"])}"')
        lines.append("")

    if "serial" in board:
        serial = board["serial"]
        if "console" in serial:
            con = serial["console"]
            lines.append("/* Serial console configuration */")
            if "baud" in con:
                lines.append(
                    f"#define OVE_SERIAL_CONSOLE_BAUD {con['baud']}")
            if "tx_pin" in con:
                lines.append(
                    f'#define OVE_SERIAL_CONSOLE_TX_PIN '
                    f'"{_c_str(con["tx_pin"])}"')
            if "rx_pin" in con:
                lines.append(
                    f'#define OVE_SERIAL_CONSOLE_RX_PIN '
                    f'"{_c_str(con["rx_pin"])}"')
            if "rx_buffer_size" in con:
                lines.append(
                    f"#define OVE_SERIAL_CONSOLE_RX_BUFFER_SIZE "
                    f"{con['rx_buffer_size']}")
            lines.append("")

    if "sdcard" in board:
        sd = board["sdcard"]
        lines.append("/* SD card configuration */")
        if "interface" in sd:
            lines.append(
                f'#define OVE_SDCARD_INTERFACE '
                f'"{_c_str(sd["interface"])}"')
        lines.append("")

    if "watchdog" in board:
        wd = board["watchdog"]
        lines.append("/* Watchdog configuration */")
        if "timeout_ms" in wd:
            lines.append(
                f"#define OVE_WATCHDOG_TIMEOUT_MS {wd['timeout_ms']}")
        lines.append("")

    # Runtime descriptor struct
    lines.append("/* Runtime board descriptor */")
    lines.append('#include "ove/board_types.h"')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    led_count = len(board.get("leds", []))
    if led_count > 0:
        lines.append(
            f"static const struct ove_led_desc "
            f"ove_board_leds[{led_count}] = {{")
        for led in board["leds"]:
            active_low = 1 if led.get("active_low", False) else 0
            lines.append(
                f"    {{ {led['port']}, {led['pin']}, {active_low} }},")
        lines.append("};")
    else:
        lines.append(
            "#define ove_board_leds "
            "((const struct ove_led_desc *)0)")
    lines.append("")

    gpio_port_count = board.get("gpio", {}).get("port_count", 0)
    gpio_pins_per_port = board.get("gpio", {}).get("pins_per_port", 16)

    lines.append(
        "static const struct ove_board_desc "
        "ove_board_descriptor = {")
    lines.append('    .name = OVE_BOARD_NAME,')
    lines.append('    .mcu_family = OVE_BOARD_MCU_FAMILY,')
    lines.append('    .mcu = OVE_BOARD_MCU,')
    lines.append(f"    .gpio_port_count = {gpio_port_count},")
    lines.append(f"    .gpio_pins_per_port = {gpio_pins_per_port},")
    lines.append(f"    .led_count = {led_count},")
    lines.append("    .leds = ove_board_leds,")
    lines.append("};")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* OVE_BOARD_DESC_H */")
    lines.append("")

    return "\n".join(lines)


def generate_board_desc(ws):
    """Generate board_desc.h from board.yaml if available."""
    board_dir = ws.board_dir
    if not board_dir:
        return

    board_yaml_path = os.path.join(board_dir, "board.yaml")
    if not os.path.isfile(board_yaml_path):
        return

    if yaml is None:
        print("Warning: pyyaml not installed, skipping board descriptor")
        return

    print("=== Generating board descriptor ===")
    with open(board_yaml_path) as f:
        board = yaml.safe_load(f)

    # Validate against schema
    schema_path = os.path.join(ws.ove_dir, "config", "schemas",
                               "board_schema.json")
    if jsonschema and os.path.isfile(schema_path):
        with open(schema_path) as f:
            schema = json.load(f)
        board_clean = {k: v for k, v in board.items() if k != "_meta"}
        try:
            jsonschema.validate(instance=board_clean, schema=schema)
        except jsonschema.ValidationError as e:
            print(f"Board YAML validation error: {e.message}")
            sys.exit(1)

    header = _generate_board_desc_header(board)
    output_path = os.path.join(ws.gen_dir, "board_desc.h")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header)
    print(f"  Generated: {output_path}")
