[package]
name = "ove-tests"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[[bin]]
name = "ove-tests"
path = "src/main.rs"

[dependencies]
ove = { path = "../../bindings/rust/ove", features = ["std", "embedded-hal", "embedded-io"], default-features = false }
embedded-hal = "1.0"
embedded-io = "0.7"
log = "0.4"
static_assertions = "1.1"
