lang: cpp
config_name: example_cpp
description: "C++ Demo"
sources:
  - src/app.cpp
includes:
  - include
defconfig:
  - CONFIG_OVE_BSP=y
  - CONFIG_OVE_LVGL=y
  - CONFIG_OVE_QUEUE=y
  - CONFIG_OVE_TIMER=y
