lang: cpp
config_name: example_net_cpp_heap
description: "C++ Networking Demo"
sources:
  - src/app.cpp
includes:
  - include
defconfig:
  - CONFIG_OVE_BSP=y
  - CONFIG_OVE_NET=y
  - CONFIG_OVE_NET_HTTP=y
  - CONFIG_OVE_NET_MQTT=y
  - CONFIG_OVE_NET_HTTPD=y
  - CONFIG_OVE_NET_SNTP=y
