[package]
name = "example_keyword_live_rust"
version = "1.0.0"
edition = "2024"
rust-version = "1.85"

[lib]
crate-type = ["staticlib"]

[dependencies]
ove = { path = "../../../../bindings/rust/ove", features = ["alloc"] }
log = "0.4"
ove-allocator = { path = "../../../../bindings/rust/ove-allocator", default-features = false }

[features]
default = []
std = ["ove/std", "ove-allocator/no_install"]
panic-handler = ["ove/panic-handler"]

