/*
 * Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of oveRTOS.
 */

#ifndef OVE_STORAGE_H
#define OVE_STORAGE_H

/**
 * @defgroup ove_storage Storage Types
 * @brief Backend-specific opaque storage types and static-allocation macros.
 *
 * This header selects the correct backend storage header and exposes:
 *
 * - **Opaque storage types** (@c ove_*_storage_t) — raw byte arrays with
 *   the correct size and alignment for each backend's primitive.  Use these
 *   with @c _init() functions for zero-heap (static) allocation.
 *
 * - **@c OVE_*_DEFINE() macros** — file-scope convenience wrappers that
 *   declare a named storage object of the correct type.
 *
 * - **@c OVE_*_DEFINE_STATIC() macros** — one-step primitives that declare
 *   a handle, allocate static storage, and register a C constructor that
 *   initialises the handle before @c main().  In heap mode they call the
 *   corresponding @c _create() function instead.
 *
 * @par Backend selection
 * The correct backend header is chosen at build time via the
 * @c CONFIG_OVE_RTOS_* defines.  Foreign-language toolchains use alternate
 * selection logic:
 *   - `__BINDGEN__` (Rust bindgen): uses exact build-time sizes from
 *     @c storage_sizes.h generated by @c ove_rust.cmake.
 *   - `__ZIG_CIMPORT__` (Zig \@cImport): uses either exact build-time sizes
 *     from @c zig_storage_sizes.h (zero-heap) or minimal 1-byte opaque types
 *     (heap mode).
 *
 * @note In zero-heap mode (@c CONFIG_OVE_ZERO_HEAP) the @c OVE_HEAP_*
 *       gates are not defined, so no heap-backed @c _create()/@c _destroy()
 *       functions are compiled.  However, each module provides macros with
 *       the same @c _create()/@c _destroy() names that generate per-call-site
 *       static storage, giving a unified API in both modes.
 * @{
 */

#include "ove/types.h"
#include "ove_config.h"

/*
 * Include the backend-specific storage header.
 *
 * __BINDGEN__      — Rust bindgen: use exact build-time-generated sizes
 *                    (required for zero-heap static allocation).
 * __ZIG_CIMPORT__  — Zig @cImport: use minimal opaque types (Zig only
 *                    passes pointer handles, never allocates storage).
 *
 * Without either flag, the real backend header is included.
 */
#if defined(__ZIG_CIMPORT__)
/* Try to include build-time storage sizes for zero-heap mode.
 * zig_storage_sizes.h is generated by ove_zig.cmake and placed
 * on the include path only for zero-heap builds. */
#if __has_include("zig_storage_sizes.h")
#include "zig_storage_sizes.h"
#endif
#endif

#if defined(__ZIG_CIMPORT__) && !defined(OVE_SIZEOF_OVE_THREAD_STORAGE)
#ifdef CONFIG_OVE_ZERO_HEAP
#error "Zero-heap mode requires storage sizes. Run cmake with ove_zig.cmake to generate zig_storage_sizes.h"
#endif
/* Zig heap mode: minimal opaques — only pointer handles are used,
 * the C backend mallocs real storage. */
#include <stdint.h>
/** @cond INTERNAL */
typedef struct { uint8_t _opaque; } ove_mutex_storage_t;
typedef struct { uint8_t _opaque; } ove_sem_storage_t;
typedef struct { uint8_t _opaque; } ove_event_storage_t;
typedef struct { uint8_t _opaque; } ove_condvar_storage_t;
typedef struct { uint8_t _opaque; } ove_thread_storage_t;
typedef struct { uint8_t _opaque; } ove_queue_storage_t;
typedef struct { uint8_t _opaque; } ove_timer_storage_t;
typedef struct { uint8_t _opaque; } ove_eventgroup_storage_t;
typedef struct { uint8_t _opaque; } ove_workqueue_storage_t;
typedef struct { uint8_t _opaque; } ove_work_storage_t;
typedef struct { uint8_t _opaque; } ove_stream_storage_t;
typedef struct { uint8_t _opaque; } ove_watchdog_storage_t;
typedef struct { uint8_t _opaque; } ove_file_storage_t;
typedef struct { uint8_t _opaque; } ove_dir_storage_t;
#ifdef CONFIG_OVE_INFER
typedef struct { uint8_t _opaque; } ove_model_storage_t;
#endif
#ifdef CONFIG_OVE_NET
typedef struct { uint8_t _opaque; } ove_socket_storage_t;
typedef struct { uint8_t _opaque; } ove_netif_storage_t;
#endif
#ifdef CONFIG_OVE_NET_TLS
typedef struct { uint8_t _opaque; } ove_tls_storage_t;
#endif
#ifdef CONFIG_OVE_NET_HTTP
typedef struct { uint8_t _opaque; } ove_http_client_storage_t;
#endif
#ifdef CONFIG_OVE_NET_MQTT
typedef struct { uint8_t _opaque; } ove_mqtt_client_storage_t;
#endif
/** @endcond */
#elif defined(__ZIG_CIMPORT__) || defined(__BINDGEN__)
/*
 * Opaque storage types for Rust bindings.
 *
 * When OVE_STORAGE_SIZES is generated at build time (by
 * ove_rust.cmake), exact per-backend sizes are used.
 * Otherwise, conservative upper bounds cover all backends.
 */
#include <stdint.h>

/**
 * @brief Internal helper macro that defines a correctly sized and aligned
 *        opaque storage struct for foreign-language bindings.
 *
 * @note This macro is an implementation detail; do not use directly.
 */
#define OVE_OPAQUE_(name, size, align) \
	typedef struct { _Alignas(align) uint8_t _opaque[size]; } name

/*
 * Sizes are generated at build time by ove_rust.cmake and injected
 * via storage_sizes.h (included by build.rs before this header).
 * If the defines are missing, the build system is misconfigured.
 */
#ifndef OVE_SIZEOF_OVE_THREAD_STORAGE
#error "Storage sizes not generated. Rust/Zig zero-heap builds require ove_{rust,zig}.cmake to produce storage sizes."
#endif

/** @cond INTERNAL */
OVE_OPAQUE_(ove_mutex_storage_t,      OVE_SIZEOF_OVE_MUTEX_STORAGE,      OVE_ALIGNOF_OVE_MUTEX_STORAGE);
OVE_OPAQUE_(ove_sem_storage_t,        OVE_SIZEOF_OVE_SEM_STORAGE,        OVE_ALIGNOF_OVE_SEM_STORAGE);
OVE_OPAQUE_(ove_event_storage_t,      OVE_SIZEOF_OVE_EVENT_STORAGE,      OVE_ALIGNOF_OVE_EVENT_STORAGE);
OVE_OPAQUE_(ove_condvar_storage_t,    OVE_SIZEOF_OVE_CONDVAR_STORAGE,    OVE_ALIGNOF_OVE_CONDVAR_STORAGE);
OVE_OPAQUE_(ove_thread_storage_t,     OVE_SIZEOF_OVE_THREAD_STORAGE,     OVE_ALIGNOF_OVE_THREAD_STORAGE);
OVE_OPAQUE_(ove_queue_storage_t,      OVE_SIZEOF_OVE_QUEUE_STORAGE,      OVE_ALIGNOF_OVE_QUEUE_STORAGE);
OVE_OPAQUE_(ove_timer_storage_t,      OVE_SIZEOF_OVE_TIMER_STORAGE,      OVE_ALIGNOF_OVE_TIMER_STORAGE);
OVE_OPAQUE_(ove_eventgroup_storage_t, OVE_SIZEOF_OVE_EVENTGROUP_STORAGE, OVE_ALIGNOF_OVE_EVENTGROUP_STORAGE);
OVE_OPAQUE_(ove_workqueue_storage_t,  OVE_SIZEOF_OVE_WORKQUEUE_STORAGE,  OVE_ALIGNOF_OVE_WORKQUEUE_STORAGE);
OVE_OPAQUE_(ove_work_storage_t,       OVE_SIZEOF_OVE_WORK_STORAGE,       OVE_ALIGNOF_OVE_WORK_STORAGE);
OVE_OPAQUE_(ove_stream_storage_t,     OVE_SIZEOF_OVE_STREAM_STORAGE,     OVE_ALIGNOF_OVE_STREAM_STORAGE);
OVE_OPAQUE_(ove_watchdog_storage_t,   OVE_SIZEOF_OVE_WATCHDOG_STORAGE,   OVE_ALIGNOF_OVE_WATCHDOG_STORAGE);
OVE_OPAQUE_(ove_file_storage_t,       OVE_SIZEOF_OVE_FILE_STORAGE,       OVE_ALIGNOF_OVE_FILE_STORAGE);
OVE_OPAQUE_(ove_dir_storage_t,        OVE_SIZEOF_OVE_DIR_STORAGE,        OVE_ALIGNOF_OVE_DIR_STORAGE);
#if defined(CONFIG_OVE_INFER) && defined(OVE_SIZEOF_OVE_MODEL_STORAGE)
OVE_OPAQUE_(ove_model_storage_t,     OVE_SIZEOF_OVE_MODEL_STORAGE,      OVE_ALIGNOF_OVE_MODEL_STORAGE);
#endif
#if defined(CONFIG_OVE_NET) && defined(OVE_SIZEOF_OVE_SOCKET_STORAGE)
OVE_OPAQUE_(ove_socket_storage_t,    OVE_SIZEOF_OVE_SOCKET_STORAGE,     OVE_ALIGNOF_OVE_SOCKET_STORAGE);
OVE_OPAQUE_(ove_netif_storage_t,     OVE_SIZEOF_OVE_NETIF_STORAGE,      OVE_ALIGNOF_OVE_NETIF_STORAGE);
#endif
#if defined(CONFIG_OVE_NET_TLS) && defined(OVE_SIZEOF_OVE_TLS_STORAGE)
OVE_OPAQUE_(ove_tls_storage_t,       OVE_SIZEOF_OVE_TLS_STORAGE,        OVE_ALIGNOF_OVE_TLS_STORAGE);
#endif
#if defined(CONFIG_OVE_NET_HTTP) && defined(OVE_SIZEOF_OVE_HTTP_CLIENT_STORAGE)
OVE_OPAQUE_(ove_http_client_storage_t, OVE_SIZEOF_OVE_HTTP_CLIENT_STORAGE, OVE_ALIGNOF_OVE_HTTP_CLIENT_STORAGE);
#endif
#if defined(CONFIG_OVE_NET_MQTT) && defined(OVE_SIZEOF_OVE_MQTT_CLIENT_STORAGE)
OVE_OPAQUE_(ove_mqtt_client_storage_t, OVE_SIZEOF_OVE_MQTT_CLIENT_STORAGE, OVE_ALIGNOF_OVE_MQTT_CLIENT_STORAGE);
#endif
/** @endcond */

#undef OVE_OPAQUE_
#else
#if defined(CONFIG_OVE_RTOS_FREERTOS)
#include "ove_storage_freertos.h"
#elif defined(CONFIG_OVE_RTOS_ZEPHYR)
#include "ove_storage_zephyr.h"
#elif defined(CONFIG_OVE_RTOS_NUTTX)
#include "ove_storage_nuttx.h"
#elif defined(CONFIG_OVE_RTOS_POSIX)
#include "ove_storage_posix.h"
#endif
#endif /* __BINDGEN__ */

/**
 * @defgroup ove_storage_heap_gates Heap Gates
 * @ingroup ove_storage
 * @brief Preprocessor flags indicating which heap-backed @c _create()/@c _destroy()
 *        functions are compiled.
 *
 * When @c CONFIG_OVE_ZERO_HEAP is not defined these macros are set to 1,
 * enabling the corresponding heap-backed @c _create()/@c _destroy() function
 * definitions.  When zero-heap is active none of these macros are defined;
 * instead, each module header provides macros with the same
 * @c _create()/@c _destroy() names that auto-generate per-call-site static
 * storage, so application code can use the unified API in either mode.
 * @{
 */
#if !defined(CONFIG_OVE_ZERO_HEAP)
#define OVE_HEAP_SYNC       1 /**< Synchronisation primitives support heap allocation. */
#define OVE_HEAP_THREAD     1 /**< Threads support heap allocation. */
#define OVE_HEAP_QUEUE      1 /**< Queues support heap allocation. */
#define OVE_HEAP_TIMER      1 /**< Timers support heap allocation. */
#define OVE_HEAP_EVENTGROUP 1 /**< Event groups support heap allocation. */
#define OVE_HEAP_WORKQUEUE  1 /**< Work queues support heap allocation. */
#define OVE_HEAP_STREAM     1 /**< Stream buffers support heap allocation. */
#define OVE_HEAP_WATCHDOG   1 /**< Watchdog timers support heap allocation. */
#define OVE_HEAP_FS         1 /**< Filesystem handles support heap allocation. */
#define OVE_HEAP_INFER      1 /**< ML inference sessions support heap allocation. */
#define OVE_HEAP_NET        1 /**< Sockets and network interfaces support heap allocation. */
#define OVE_HEAP_NET_TLS    1 /**< TLS sessions support heap allocation. */
#define OVE_HEAP_NET_HTTP   1 /**< HTTP clients support heap allocation. */
#define OVE_HEAP_NET_MQTT   1 /**< MQTT clients support heap allocation. */
#endif /* !CONFIG_OVE_ZERO_HEAP */
/** @} */

/**
 * @brief Assertion macro used by static constructor macros on init failure.
 *
 * Defaults to @c assert().  Define @c OVE_STATIC_INIT_ASSERT before
 * including any oveRTOS header to override with a custom handler
 * (e.g. a board-specific panic routine).
 */
#include <assert.h>

#ifndef OVE_STATIC_INIT_ASSERT
#define OVE_STATIC_INIT_ASSERT(cond) assert(cond)
#endif

/**
 * @defgroup ove_storage_define OVE_*_DEFINE Macros
 * @ingroup ove_storage
 * @brief File-scope static storage object declarations.
 *
 * Each macro declares a @c static storage variable of the correct backend
 * type.  Pass its address to the corresponding @c _init() function:
 *
 * @code
 *   OVE_MUTEX_DEFINE(my_mutex_storage);
 *   ove_mutex_t my_mutex;
 *   ove_mutex_init(&my_mutex, &my_mutex_storage);
 * @endcode
 * @{
 */

/**
 * @brief Declare a static mutex storage variable named @p name.
 */
#define OVE_MUTEX_DEFINE(name) \
	static ove_mutex_storage_t name

/**
 * @brief Declare a static semaphore storage variable named @p name.
 */
#define OVE_SEM_DEFINE(name) \
	static ove_sem_storage_t name

/**
 * @brief Declare a static event storage variable named @p name.
 */
#define OVE_EVENT_DEFINE(name) \
	static ove_event_storage_t name

/**
 * @brief Declare a static condition variable storage variable named @p name.
 */
#define OVE_CONDVAR_DEFINE(name) \
	static ove_condvar_storage_t name

/* Backend-specific thread stack definition (Zephyr needs K_THREAD_STACK_DEFINE) */
#ifndef OVE_THREAD_STACK_DEFINE_
/**
 * @brief Declare a static thread stack array named @p name with size @p size.
 *
 * @note Overridden by backends that require special alignment (e.g. Zephyr MPU).
 */
#define OVE_THREAD_STACK_DEFINE_(name, size) \
	static uint8_t name[(size)]
#endif

/** @cond INTERNAL */
/* Block-scope static variant — safe inside ({...}) statement expressions. */
#ifndef OVE_THREAD_STACK_BLOCK_STATIC_
#define OVE_THREAD_STACK_BLOCK_STATIC_(name, size) \
	static uint8_t __attribute__((aligned(8))) name[(size)]
#endif
/** @endcond */

/* Class-member variant (no 'static') — for C++ class-embedded stacks.
 * Overridden by backends that need special alignment (e.g. Zephyr MPU). */
#ifndef OVE_THREAD_STACK_MEMBER_
/**
 * @brief Declare a non-static (class-member) thread stack array.
 *
 * Use inside a C++ struct or class body where @c static is not applicable.
 *
 * @note Overridden by backends that require special alignment (e.g. Zephyr MPU).
 */
#define OVE_THREAD_STACK_MEMBER_(name, size) uint8_t name[size]
#endif

/**
 * @brief Declare a static thread storage variable and its stack.
 *
 * @param name            Variable name for the thread storage.
 * @param stack_size_bytes Stack size in bytes.
 */
#define OVE_THREAD_DEFINE(name, stack_size_bytes) \
	static ove_thread_storage_t name; \
	OVE_THREAD_STACK_DEFINE_(name##_stack, stack_size_bytes)

/**
 * @brief Declare a static queue storage variable and its backing buffer.
 *
 * @param name    Variable name for the queue storage.
 * @param item_sz Size of each queue item in bytes.
 * @param max     Maximum number of items in the queue.
 */
#define OVE_QUEUE_DEFINE(name, item_sz, max) \
	static ove_queue_storage_t name; \
	static uint8_t name##_buffer[(item_sz) * (max)]

/**
 * @brief Declare a static timer storage variable named @p name.
 */
#define OVE_TIMER_DEFINE(name) \
	static ove_timer_storage_t name

/**
 * @brief Declare a static event group storage variable named @p name.
 */
#define OVE_EVENTGROUP_DEFINE(name) \
	static ove_eventgroup_storage_t name

/**
 * @brief Declare a static work queue storage variable and its stack.
 *
 * @param name            Variable name for the work queue storage.
 * @param stack_size_bytes Stack size in bytes for the work queue thread.
 */
#define OVE_WORKQUEUE_DEFINE(name, stack_size_bytes) \
	static ove_workqueue_storage_t name; \
	static uint8_t name##_stack[stack_size_bytes]

/**
 * @brief Declare a static stream buffer storage variable and its backing buffer.
 *
 * @param name     Variable name for the stream storage.
 * @param buf_size Stream buffer capacity in bytes.
 */
#define OVE_STREAM_DEFINE(name, buf_size) \
	static ove_stream_storage_t name; \
	static uint8_t name##_buffer[(buf_size) + 1]

/**
 * @brief Declare a static watchdog storage variable named @p name.
 */
#define OVE_WATCHDOG_DEFINE(name) \
	static ove_watchdog_storage_t name

#ifdef CONFIG_OVE_INFER
/**
 * @brief Declare a static model storage variable named @p name.
 */
#define OVE_MODEL_DEFINE(name) \
	static ove_model_storage_t name

/**
 * @brief Declare a 16-byte-aligned static tensor arena of @p size bytes.
 */
#define OVE_MODEL_ARENA_DEFINE(name, size) \
	static uint8_t __attribute__((aligned(16))) name[(size)]
#endif /* CONFIG_OVE_INFER */

/** @} */ /* ove_storage_define */

/**
 * @defgroup ove_storage_define_static OVE_*_DEFINE_STATIC Macros
 * @ingroup ove_storage
 * @brief One-step static primitive declaration with automatic initialisation.
 *
 * Each macro declares a handle and a C constructor (@c __attribute__((constructor)))
 * that initialises the handle before @c main().  No runtime init boilerplate or
 * @c \#ifdef guards are needed.
 *
 * - In **zero-heap mode** (@c CONFIG_OVE_ZERO_HEAP) the constructor calls the
 *   corresponding @c _init() function with static storage.
 * - In **heap mode** the constructor calls @c _create() so the macros work on
 *   every backend without modification.
 *
 * Usage:
 * @code
 *   OVE_QUEUE_DEFINE_STATIC(my_q, sizeof(int), 8);
 *   // my_q is ready to use in any function.
 * @endcode
 * @{
 */

/** @cond INTERNAL */
/* Helper: constructor preamble */
#define OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
	__attribute__((used)) \
	static void __attribute__((constructor)) \
	_##name##_ctor(void) {

#define OVE_DEFINE_STATIC_CTOR_END_(name) \
		OVE_STATIC_INIT_ASSERT(_err == OVE_OK); \
	}
/** @endcond */

#ifdef CONFIG_OVE_ZERO_HEAP
/* ── Zero-heap: use static storage + _init() ─────────────────────────── */

/**
 * @brief Declare and auto-initialise a static mutex.
 *
 * @param name  Variable name for the resulting @c ove_mutex_t handle.
 */
#define OVE_MUTEX_DEFINE_STATIC(name) \
	static ove_mutex_storage_t _##name##_storage; \
	static ove_mutex_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_mutex_init(&name, &_##name##_storage); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static recursive mutex.
 *
 * @param name  Variable name for the resulting @c ove_mutex_t handle.
 */
#define OVE_RECURSIVE_MUTEX_DEFINE_STATIC(name) \
	static ove_mutex_storage_t _##name##_storage; \
	static ove_mutex_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_recursive_mutex_init(&name, \
			&_##name##_storage); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static semaphore.
 *
 * @param name     Variable name for the resulting @c ove_sem_t handle.
 * @param initial  Initial semaphore count.
 * @param max      Maximum semaphore count.
 */
#define OVE_SEM_DEFINE_STATIC(name, initial, max) \
	static ove_sem_storage_t _##name##_storage; \
	static ove_sem_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_sem_init(&name, &_##name##_storage, \
			(initial), (max)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static event object.
 *
 * @param name  Variable name for the resulting @c ove_event_t handle.
 */
#define OVE_EVENT_DEFINE_STATIC(name) \
	static ove_event_storage_t _##name##_storage; \
	static ove_event_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_event_init(&name, &_##name##_storage); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static condition variable.
 *
 * @param name  Variable name for the resulting @c ove_condvar_t handle.
 */
#define OVE_CONDVAR_DEFINE_STATIC(name) \
	static ove_condvar_storage_t _##name##_storage; \
	static ove_condvar_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_condvar_init(&name, &_##name##_storage); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static thread.
 *
 * @param hname     Variable name for the resulting @c ove_thread_t handle.
 * @param stack_sz  Thread stack size in bytes.
 * @param fn        Thread entry function.
 * @param ctx       Argument passed to @p fn.
 * @param prio      Thread priority.
 * @param tname     Human-readable thread name string.
 */
#define OVE_THREAD_DEFINE_STATIC(hname, stack_sz, fn, ctx, prio, tname) \
	static ove_thread_storage_t _##hname##_storage; \
	OVE_THREAD_STACK_DEFINE_(_##hname##_stack, stack_sz); \
	static ove_thread_t hname; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(hname) \
		struct ove_thread_desc _desc = { \
			.name = (tname), \
			.entry = (fn), \
			.arg = (ctx), \
			.priority = (prio), \
			.stack_size = (stack_sz), \
			.stack = _##hname##_stack, \
		}; \
		int _err = ove_thread_init(&hname, \
			&_##hname##_storage, &_desc); \
	OVE_DEFINE_STATIC_CTOR_END_(hname)

/**
 * @brief Declare and auto-initialise a static message queue.
 *
 * @param name     Variable name for the resulting @c ove_queue_t handle.
 * @param item_sz  Size of each queue item in bytes.
 * @param max      Maximum number of items in the queue.
 */
#define OVE_QUEUE_DEFINE_STATIC(name, item_sz, max) \
	static ove_queue_storage_t _##name##_storage; \
	static uint8_t _##name##_buf[(item_sz) * (max)]; \
	static ove_queue_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_queue_init(&name, &_##name##_storage, \
			_##name##_buf, (item_sz), (max)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static timer.
 *
 * @param name       Variable name for the resulting @c ove_timer_t handle.
 * @param cb         Timer expiry callback.
 * @param user_data  Opaque pointer forwarded to @p cb.
 * @param period_ms  Timer period in milliseconds.
 * @param one_shot   Non-zero for a one-shot timer, zero for periodic.
 */
#define OVE_TIMER_DEFINE_STATIC(name, cb, user_data, period_ms, one_shot) \
	static ove_timer_storage_t _##name##_storage; \
	static ove_timer_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_timer_init(&name, &_##name##_storage, \
			(cb), (user_data), (period_ms), (one_shot)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static event group.
 *
 * @param name  Variable name for the resulting @c ove_eventgroup_t handle.
 */
#define OVE_EVENTGROUP_DEFINE_STATIC(name) \
	static ove_eventgroup_storage_t _##name##_storage; \
	static ove_eventgroup_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_eventgroup_init(&name, \
			&_##name##_storage); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static work queue.
 *
 * @param name      Variable name for the resulting @c ove_workqueue_t handle.
 * @param stack_sz  Stack size in bytes for the work queue thread.
 * @param wq_name   Human-readable work queue name string.
 * @param prio      Thread priority for the work queue thread.
 */
#define OVE_WORKQUEUE_DEFINE_STATIC(name, stack_sz, wq_name, prio) \
	static ove_workqueue_storage_t _##name##_storage; \
	static uint8_t _##name##_stack[(stack_sz)]; \
	static ove_workqueue_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_workqueue_init(&name, \
			&_##name##_storage, (wq_name), (prio), \
			(stack_sz), _##name##_stack); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static work item.
 *
 * @param name     Variable name for the resulting @c ove_work_t handle.
 * @param handler  Work handler function invoked when the item is executed.
 */
#define OVE_WORK_DEFINE_STATIC(name, handler) \
	static ove_work_storage_t _##name##_storage; \
	static ove_work_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_work_init_static(&name, \
			&_##name##_storage, (handler)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static stream buffer.
 *
 * @param name     Variable name for the resulting @c ove_stream_t handle.
 * @param buf_sz   Stream buffer capacity in bytes.
 * @param trigger  Minimum bytes required before a blocked reader is unblocked.
 */
#define OVE_STREAM_DEFINE_STATIC(name, buf_sz, trigger) \
	static ove_stream_storage_t _##name##_storage; \
	static uint8_t _##name##_buf[(buf_sz) + 1]; \
	static ove_stream_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_stream_init(&name, &_##name##_storage, \
			_##name##_buf, (buf_sz), (trigger)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static watchdog timer.
 *
 * @param name        Variable name for the resulting @c ove_watchdog_t handle.
 * @param timeout_ms  Watchdog timeout in milliseconds.
 */
#define OVE_WATCHDOG_DEFINE_STATIC(name, timeout_ms) \
	static ove_watchdog_storage_t _##name##_storage; \
	static ove_watchdog_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_watchdog_init(&name, \
			&_##name##_storage, (timeout_ms)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

#ifdef CONFIG_OVE_INFER
/**
 * @brief Declare and auto-initialise a static ML model (zero-heap).
 *
 * @param name        Variable name for the resulting @c ove_model_t handle.
 * @param model_ptr   Pointer to the .tflite FlatBuffer data.
 * @param model_sz    Size of the FlatBuffer in bytes.
 * @param arena_sz    Tensor arena size in bytes (must be compile-time constant).
 */
#define OVE_MODEL_DEFINE_STATIC(name, model_ptr, model_sz, arena_sz) \
	static ove_model_storage_t _##name##_storage; \
	static uint8_t __attribute__((aligned(16))) _##name##_arena[(arena_sz)]; \
	static ove_model_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		struct ove_model_config _cfg = { \
			.model_data = (model_ptr), \
			.model_size = (model_sz), \
			.arena_size = (arena_sz), \
		}; \
		int _err = ove_model_init(&name, \
			&_##name##_storage, _##name##_arena, &_cfg); \
	OVE_DEFINE_STATIC_CTOR_END_(name)
#endif /* CONFIG_OVE_INFER */

#else /* !CONFIG_OVE_ZERO_HEAP */
/* ── Heap mode: use _create() — works on all backends ────────────────── */

/**
 * @brief Declare and auto-initialise a static mutex (heap mode).
 *
 * @param name  Variable name for the resulting @c ove_mutex_t handle.
 */
#define OVE_MUTEX_DEFINE_STATIC(name) \
	static ove_mutex_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_mutex_create(&name); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static recursive mutex (heap mode).
 *
 * @param name  Variable name for the resulting @c ove_mutex_t handle.
 */
#define OVE_RECURSIVE_MUTEX_DEFINE_STATIC(name) \
	static ove_mutex_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_recursive_mutex_create(&name); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static semaphore (heap mode).
 *
 * @param name     Variable name for the resulting @c ove_sem_t handle.
 * @param initial  Initial semaphore count.
 * @param max      Maximum semaphore count.
 */
#define OVE_SEM_DEFINE_STATIC(name, initial, max) \
	static ove_sem_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_sem_create(&name, (initial), (max)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static event object (heap mode).
 *
 * @param name  Variable name for the resulting @c ove_event_t handle.
 */
#define OVE_EVENT_DEFINE_STATIC(name) \
	static ove_event_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_event_create(&name); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static condition variable (heap mode).
 *
 * @param name  Variable name for the resulting @c ove_condvar_t handle.
 */
#define OVE_CONDVAR_DEFINE_STATIC(name) \
	static ove_condvar_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_condvar_create(&name); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static thread (heap mode).
 *
 * @param hname     Variable name for the resulting @c ove_thread_t handle.
 * @param stack_sz  Thread stack size in bytes.
 * @param fn        Thread entry function.
 * @param ctx       Argument passed to @p fn.
 * @param prio      Thread priority.
 * @param tname     Human-readable thread name string.
 */
#define OVE_THREAD_DEFINE_STATIC(hname, stack_sz, fn, ctx, prio, tname) \
	static ove_thread_t hname; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(hname) \
		struct ove_thread_desc _desc = { \
			.name = (tname), \
			.entry = (fn), \
			.arg = (ctx), \
			.priority = (prio), \
			.stack_size = (stack_sz), \
		}; \
		int _err = ove_thread_create_(&hname, &_desc); \
	OVE_DEFINE_STATIC_CTOR_END_(hname)

/**
 * @brief Declare and auto-initialise a static message queue (heap mode).
 *
 * @param name     Variable name for the resulting @c ove_queue_t handle.
 * @param item_sz  Size of each queue item in bytes.
 * @param max      Maximum number of items in the queue.
 */
#define OVE_QUEUE_DEFINE_STATIC(name, item_sz, max) \
	static ove_queue_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_queue_create(&name, (item_sz), (max)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static timer (heap mode).
 *
 * @param name       Variable name for the resulting @c ove_timer_t handle.
 * @param cb         Timer expiry callback.
 * @param user_data  Opaque pointer forwarded to @p cb.
 * @param period_ms  Timer period in milliseconds.
 * @param one_shot   Non-zero for a one-shot timer, zero for periodic.
 */
#define OVE_TIMER_DEFINE_STATIC(name, cb, user_data, period_ms, one_shot) \
	static ove_timer_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_timer_create(&name, \
			(cb), (user_data), (period_ms), (one_shot)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static event group (heap mode).
 *
 * @param name  Variable name for the resulting @c ove_eventgroup_t handle.
 */
#define OVE_EVENTGROUP_DEFINE_STATIC(name) \
	static ove_eventgroup_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_eventgroup_create(&name); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static work queue (heap mode).
 *
 * @param name      Variable name for the resulting @c ove_workqueue_t handle.
 * @param stack_sz  Stack size in bytes for the work queue thread.
 * @param wq_name   Human-readable work queue name string.
 * @param prio      Thread priority for the work queue thread.
 */
#define OVE_WORKQUEUE_DEFINE_STATIC(name, stack_sz, wq_name, prio) \
	static ove_workqueue_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_workqueue_create(&name, \
			(wq_name), (prio), (stack_sz)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static work item (heap mode).
 *
 * @param name     Variable name for the resulting @c ove_work_t handle.
 * @param handler  Work handler function invoked when the item is executed.
 */
#define OVE_WORK_DEFINE_STATIC(name, handler) \
	static ove_work_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_work_init(&name, (handler)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static stream buffer (heap mode).
 *
 * @param name     Variable name for the resulting @c ove_stream_t handle.
 * @param buf_sz   Stream buffer capacity in bytes.
 * @param trigger  Minimum bytes required before a blocked reader is unblocked.
 */
#define OVE_STREAM_DEFINE_STATIC(name, buf_sz, trigger) \
	static ove_stream_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_stream_create(&name, \
			(buf_sz), (trigger)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

/**
 * @brief Declare and auto-initialise a static watchdog timer (heap mode).
 *
 * @param name        Variable name for the resulting @c ove_watchdog_t handle.
 * @param timeout_ms  Watchdog timeout in milliseconds.
 */
#define OVE_WATCHDOG_DEFINE_STATIC(name, timeout_ms) \
	static ove_watchdog_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		int _err = ove_watchdog_create(&name, (timeout_ms)); \
	OVE_DEFINE_STATIC_CTOR_END_(name)

#ifdef CONFIG_OVE_INFER
/**
 * @brief Declare and auto-initialise a static ML model (heap mode).
 *
 * @param name        Variable name for the resulting @c ove_model_t handle.
 * @param model_ptr   Pointer to the .tflite FlatBuffer data.
 * @param model_sz    Size of the FlatBuffer in bytes.
 * @param arena_sz    Tensor arena size in bytes.
 */
#define OVE_MODEL_DEFINE_STATIC(name, model_ptr, model_sz, arena_sz) \
	static ove_model_t name; \
	OVE_DEFINE_STATIC_CTOR_BEGIN_(name) \
		struct ove_model_config _cfg = { \
			.model_data = (model_ptr), \
			.model_size = (model_sz), \
			.arena_size = (arena_sz), \
		}; \
		int _err = ove_model_create(&name, &_cfg); \
	OVE_DEFINE_STATIC_CTOR_END_(name)
#endif /* CONFIG_OVE_INFER */

#endif /* CONFIG_OVE_ZERO_HEAP */

/** @} */ /* ove_storage_define_static */

/** @} */ /* ove_storage */

#endif /* OVE_STORAGE_H */
