#!/usr/bin/env python3

# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""Cross-binding benchmark comparison report.

Reads benchmark stdout dumps that contain JSON envelopes
(`###BENCH_JSON_BEGIN` / `###BENCH_JSON_END` sentinels emitted when
CONFIG_OVE_BENCHMARK_OUTPUT_JSON=y) and produces a Markdown table
joining cases across the C / C++ / Rust / Zig bindings.

When a `native_posix` (or other native_*) suite is present, its rows
are emitted alongside the wrapper rows so the reader can see at a
glance "wrapper vs raw API: ±X ns".

Usage:
  bench_compare.py --input <bench-stdout-or-json-file> ...
                   [--output <report.md>] [--threshold-pct N]

Each input file may be:
  - The raw stdout of one bench run (sentinels found and parsed); OR
  - A bare JSON file containing one suite per object on its own line.
The "binding" field of each JSON envelope determines which column the
case lands in; "rtos" is required to be consistent across all inputs.
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path


JSON_BLOCK_RE = re.compile(
    r"###BENCH_JSON_BEGIN\s*\n(.+?)\n###BENCH_JSON_END",
    re.DOTALL,
)


def extract_envelopes(text):
    """Yield parsed JSON suite envelopes from a stdout dump."""
    for m in JSON_BLOCK_RE.finditer(text):
        try:
            yield json.loads(m.group(1).strip())
        except json.JSONDecodeError as e:
            print(f"warning: malformed JSON envelope skipped: {e}",
                  file=sys.stderr)


def load_inputs(paths):
    """Return dict: rtos -> {binding -> {(suite, case) -> case_dict}}."""
    by_rtos = defaultdict(lambda: defaultdict(dict))
    for path in paths:
        text = Path(path).read_text()
        for suite in extract_envelopes(text):
            rtos = suite.get("rtos", "?")
            binding = suite.get("binding", "?")
            sname = suite.get("suite", "?")
            for case in suite.get("cases", []):
                key = (sname, case.get("name", "?"))
                by_rtos[rtos][binding][key] = case
    return by_rtos


def fmt_ns(n):
    if n is None:
        return "—"
    if n >= 1_000_000:
        return f"{n / 1_000_000:.2f} ms"
    if n >= 1_000:
        return f"{n / 1_000:.1f} µs"
    return f"{n} ns"


def fmt_delta_pct(wrapper, baseline):
    if wrapper is None or baseline is None or baseline == 0:
        return "—"
    pct = 100.0 * (wrapper - baseline) / baseline
    sign = "+" if pct >= 0 else ""
    return f"{sign}{pct:.1f}%"


def case_metric(case):
    """Return the comparison metric for a case (trimmed_mean preferred,
    avg_ns fallback). For memory cases, use heap_delta."""
    if case is None:
        return None
    if case.get("type") == "memory":
        return case.get("heap_delta")
    return case.get("trimmed_mean_ns") or case.get("avg_ns")


def build_report(by_rtos, threshold_pct):
    lines = []
    lines.append("# oveRTOS Cross-Binding Benchmark Comparison\n")
    lines.append(
        "Generated by `scripts/bench_compare.py`. "
        "Trimmed-mean (top 1% dropped) when available, else avg. "
        "Delta column is `(binding − C) / C` — values within "
        f"±{threshold_pct}% are within typical measurement noise.\n"
    )
    lines.append(
        "**Note on `native_*` rows in the main table.** "
        "`bench_native_posix.c` is C code calling raw pthread/sem APIs, "
        "compiled identically into every binary. The CPP/RUST/ZIG "
        "columns for those rows are *the same C code measured in three "
        "different processes* — they reflect cross-run scheduler noise, "
        "not any binding-level difference. The meaningful number is the "
        "**within-run wrapper-vs-native delta** in the dedicated section "
        "below each RTOS table.\n"
    )

    BINDING_ORDER = ["c", "cpp", "rust", "zig"]

    for rtos in sorted(by_rtos.keys()):
        by_binding = by_rtos[rtos]
        bindings_present = [b for b in BINDING_ORDER if b in by_binding]
        if not bindings_present:
            continue
        lines.append(f"\n## RTOS: {rtos}\n")

        # Determine the union of (suite, case) keys, preserving suite/case
        # ordering as observed in C (the canonical baseline) when present.
        all_keys = []
        seen = set()
        c_cases = by_binding.get("c", {})
        for k in c_cases.keys():
            all_keys.append(k)
            seen.add(k)
        for b in bindings_present:
            for k in by_binding[b].keys():
                if k not in seen:
                    all_keys.append(k)
                    seen.add(k)

        # Header: binding columns + delta columns (vs C, only for non-C).
        header = ["Suite", "Case"]
        for b in bindings_present:
            header.append(b.upper())
            if b != "c":
                header.append(f"Δ {b.upper()}")
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "|".join("---" for _ in header) + "|")

        for suite_name, case_name in all_keys:
            row = [suite_name, case_name]
            c_metric = case_metric(c_cases.get((suite_name, case_name)))
            for b in bindings_present:
                cdict = by_binding[b].get((suite_name, case_name))
                metric = case_metric(cdict)
                if cdict is None:
                    row.append("—")
                elif cdict.get("type") == "memory":
                    row.append(f"{metric} B" if metric is not None else "—")
                else:
                    row.append(fmt_ns(metric))
                if b != "c":
                    if cdict is None or cdict.get("type") == "memory":
                        row.append("—")
                    else:
                        row.append(fmt_delta_pct(metric, c_metric))
            lines.append("| " + " | ".join(row) + " |")

        # Summary block: outliers vs C (>threshold or <-threshold).
        notable = []
        for k in all_keys:
            c_dict = c_cases.get(k)
            if c_dict is None or c_dict.get("type") == "memory":
                continue
            c_v = case_metric(c_dict)
            if not c_v:
                continue
            for b in bindings_present:
                if b == "c":
                    continue
                wd = by_binding[b].get(k)
                wv = case_metric(wd)
                if not wv:
                    continue
                pct = 100.0 * (wv - c_v) / c_v
                if abs(pct) > threshold_pct:
                    notable.append((b.upper(), k[0], k[1], pct, wv, c_v))

        if notable:
            lines.append(
                f"\n**Cases with |Δ| > {threshold_pct}% vs C:**\n"
            )
            for b, suite, case, pct, wv, cv in sorted(
                    notable, key=lambda r: -abs(r[3])):
                lines.append(
                    f"- **{b}** `{suite}/{case}` "
                    f"{wv} vs {cv} ({'+' if pct >= 0 else ''}{pct:.1f}%)"
                )
        else:
            lines.append(
                f"\nAll non-memory cases within ±{threshold_pct}% of C.\n"
            )

        # Wrapper-vs-native within-run deltas — each row is one
        # (binding × operation) pair from a single benchmark process,
        # so per-run scheduler noise cancels and the Δ column is a
        # clean estimate of "wrapper code path − raw API code path"
        # in nanoseconds.
        #
        # Categories: threading, mutex, semaphore, condvar/event, IPC.
        # Native baseline suite name is detected per binding — we have
        # native_posix on POSIX builds and native_freertos on FreeRTOS
        # builds.  Both share identical case-name suffixes so a single
        # template works for either.  Cases without a meaningful raw
        # equivalent (event groups, workqueues — neither is a standard
        # POSIX or FreeRTOS primitive in the same shape) are absent.
        # IPC caveat differs by RTOS (POSIX = kernel pipe vs
        # user-space ring; FreeRTOS = native xQueue / xStreamBuffer);
        # the section header notes this.
        _WRAPPER_NATIVE_TEMPLATES = [
            # (label, wrapper_key, native_case_suffix)
            ("Thread yield",                ("thread", "yield"),                          "thread_yield"),
            ("Thread sleep 1ms",            ("thread", "sleep_1ms"),                      "thread_sleep_1ms"),
            ("Thread create+destroy",       ("thread", "create_destroy"),                 "thread_create_destroy"),
            ("Thread context_switch (2t)",  ("thread", "context_switch"),                 "thread_context_switch"),
            ("Mutex lock+unlock",           ("sync",   "mutex_lock_unlock"),              "mutex_lock_unlock"),
            ("Mutex create+destroy",        ("sync",   "mutex_create_destroy"),           "mutex_create_destroy"),
            ("Mutex contention (2t)",       ("sync",   "mutex_contention_2t"),            "mutex_contention_2t"),
            ("Recursive mutex lock+unlock", ("sync",   "recursive_mutex_lock_unlock"),    "recursive_mutex_lock_unlock"),
            ("Sem take+give",               ("sync",   "sem_take_give"),                  "sem_take_give"),
            ("Sem create+destroy",          ("sync",   "sem_create_destroy"),             "sem_create_destroy"),
            ("Condvar signal+wait",         ("sync",   "condvar_signal_wait"),            "condvar_signal_wait"),
            ("Event signal+wait",           ("sync",   "event_signal_wait"),              "event_signal_wait"),
            ("Queue send+receive",          ("queue",  "send_receive"),                   "queue_send_receive"),
            ("Queue create+destroy",        ("queue",  "create_destroy"),                 "queue_create_destroy"),
            ("Stream send+recv 64B",        ("stream", "send_recv_64B"),                  "stream_send_recv_64B"),
        ]
        # Detect which native suite is present per binding (one of
        # native_posix, native_freertos) and build the concrete pair
        # list.  All bindings in a single RTOS report share the same
        # native suite name, so we resolve it from any binding's keys.
        native_suite = None
        for b in bindings_present:
            for sname, _ in by_binding[b].keys():
                if sname.startswith("native_"):
                    native_suite = sname
                    break
            if native_suite:
                break
        WRAPPER_NATIVE_PAIRS = [
            (label, w_key, (native_suite, "native_" + suffix))
            for (label, w_key, suffix) in _WRAPPER_NATIVE_TEMPLATES
        ] if native_suite else []
        # Per-binding wrapper labels (rendered in the "Wrapper called"
        # column).  Keyed by (suite, case) so create_destroy /
        # send_receive don't collide between thread vs queue vs stream.
        WRAPPER_LABELS = {
            ("sync",   "mutex_lock_unlock"):           {"c": "ove_mutex_lock+unlock",       "cpp": "ove::Mutex::lock+unlock",         "rust": "ove::Mutex::lock+unlock",       "zig": "ove.Mutex.lock+unlock"},
            ("sync",   "mutex_create_destroy"):        {"c": "ove_mutex_create+destroy",    "cpp": "ove::Mutex (ctor+dtor)",          "rust": "ove::Mutex (new+drop)",         "zig": "ove.Mutex.create+destroy"},
            ("sync",   "mutex_contention_2t"):         {"c": "ove_mutex_lock+unlock (×2t)", "cpp": "ove::Mutex::lock+unlock (×2t)",   "rust": "ove::Mutex::lock+unlock (×2t)", "zig": "ove.Mutex.lock+unlock (×2t)"},
            ("sync",   "recursive_mutex_lock_unlock"): {"c": "ove_rmtx_lock+unlock",        "cpp": "ove::RMutex::lock+unlock",        "rust": "ove::RMutex::lock+unlock",      "zig": "ove.RMutex.lock+unlock"},
            ("sync",   "sem_take_give"):               {"c": "ove_sem_take+give",           "cpp": "ove::Sem::take+give",             "rust": "ove::Sem::take+give",           "zig": "ove.Sem.take+give"},
            ("sync",   "sem_create_destroy"):          {"c": "ove_sem_create+destroy",      "cpp": "ove::Sem (ctor+dtor)",            "rust": "ove::Sem (new+drop)",           "zig": "ove.Sem.create+destroy"},
            ("sync",   "condvar_signal_wait"):         {"c": "ove_condvar_signal+wait",     "cpp": "ove::Condvar::signal+wait",       "rust": "ove::Condvar::signal+wait",     "zig": "ove.Condvar.signal+wait"},
            ("sync",   "event_signal_wait"):           {"c": "ove_event_signal+wait",       "cpp": "ove::Event::signal+wait",         "rust": "ove::Event::signal+wait",       "zig": "ove.Event.signal+wait"},
            ("thread", "yield"):                       {"c": "ove_thread_yield",            "cpp": "ove::Thread::yield",              "rust": "ove::Thread::yield",            "zig": "ove.Thread.yield"},
            ("thread", "sleep_1ms"):                   {"c": "ove_thread_sleep_ms(1)",      "cpp": "ove::Thread::sleep_ms(1)",        "rust": "ove::Thread::sleep_ms(1)",      "zig": "ove.Thread.sleepMs(1)"},
            ("thread", "create_destroy"):              {"c": "ove_thread_create+destroy",   "cpp": "ove::Thread (ctor+dtor)",         "rust": "ove::Thread::spawn+join",       "zig": "ove.Thread.spawn+join"},
            ("thread", "context_switch"):              {"c": "ove ping-pong (2t)",          "cpp": "ove ping-pong (2t)",              "rust": "ove ping-pong (2t)",            "zig": "ove ping-pong (2t)"},
            ("queue",  "send_receive"):                {"c": "ove_queue_send+receive",      "cpp": "ove::Queue::send+recv",           "rust": "ove::Queue::send+recv",         "zig": "ove.Queue.send+recv"},
            ("queue",  "create_destroy"):              {"c": "ove_queue_create+destroy",    "cpp": "ove::Queue (ctor+dtor)",          "rust": "ove::Queue (new+drop)",         "zig": "ove.Queue.create+destroy"},
            ("stream", "send_recv_64B"):               {"c": "ove_stream_send+recv 64B",    "cpp": "ove::Stream::send+recv 64B",      "rust": "ove::Stream::send+recv 64B",    "zig": "ove.Stream.send+recv 64B"},
        }
        wn_rows = []
        for label, w_key, n_key in WRAPPER_NATIVE_PAIRS:
            for b in bindings_present:
                w = case_metric(by_binding[b].get(w_key))
                n = case_metric(by_binding[b].get(n_key))
                if w is None or n is None:
                    continue
                delta = w - n
                sign = "+" if delta >= 0 else ""
                lbl_map = WRAPPER_LABELS.get(w_key, {})
                wrapper_label = lbl_map.get(b, w_key[1])
                wn_rows.append([
                    label,
                    b.upper(),
                    wrapper_label,
                    f"{w} ns",
                    f"{n} ns",
                    f"{sign}{delta} ns",
                ])

        if wn_rows:
            native_label = {
                "native_posix":    "pthread",
                "native_freertos": "FreeRTOS API",
                "native_nuttx":    "NuttX API",
                "native_zephyr":   "Zephyr API",
            }.get(native_suite, "native API")
            ipc_caveat = {
                "native_posix": (
                    "**IPC caveat.** oveRTOS queue and stream are user-space "
                    "ring buffers; the closest standard POSIX IPC primitive "
                    "is `pipe()`, which goes through the kernel.  Large "
                    "negative Δ on `Queue *` / `Stream *` rows therefore "
                    "reflects oveRTOS staying in user space, *not* a "
                    "wrapper-layer effect.  Event groups and workqueues "
                    "have no native POSIX equivalent and are intentionally "
                    "absent from this table.\n"
                ),
                "native_freertos": (
                    "**IPC caveat.** Both oveRTOS queue and the FreeRTOS "
                    "`xQueue*` / `xStreamBuffer*` baselines run in-kernel "
                    "on Cortex-M, so wrapper-vs-native Δ on `Queue *` / "
                    "`Stream *` rows reflects pure binding overhead "
                    "(no user-space-vs-kernel asymmetry like on POSIX).  "
                    "Event groups (FreeRTOS xEventGroup* mirrors oveRTOS "
                    "1:1, uninformative) and workqueues (no FreeRTOS "
                    "primitive) are intentionally absent.\n"
                ),
                "native_zephyr": (
                    "**IPC caveat.** Zephyr's `k_msgq` is the kernel "
                    "message queue (semantically narrower than the "
                    "wrapper's user-space ring), and `k_pipe` is the "
                    "kernel byte-stream primitive (the closest "
                    "analogue to oveRTOS stream).  Both run in-kernel "
                    "on Cortex-M, so wrapper-vs-native Δ on `Queue *` / "
                    "`Stream *` rows reflects the binding overhead "
                    "rather than user-space-vs-kernel asymmetry.  "
                    "Event groups have no native peer (Zephyr's "
                    "k_event mirrors oveRTOS event 1:1, uninformative "
                    "as a comparison row); workqueues likewise.\n"
                ),
                "native_nuttx": (
                    "**IPC caveat.** NuttX's `Queue *` native baseline "
                    "uses `mq_*` (POSIX message queue, kernel-side via "
                    "VFS path registration under `/var/mqueue/`), while "
                    "oveRTOS queue on NuttX is a user-space ring buffer "
                    "over `pthread_mutex+cond` — semantically narrower "
                    "than mq.  Large negative Δ on `Queue *` rows "
                    "reflects that semantic asymmetry, not wrapper "
                    "magic.  `Stream *` rows have no native peer at "
                    "all: oveRTOS stream on NuttX is itself a user-"
                    "space ring buffer over pthread_mutex+cond, and "
                    "NuttX has no kernel byte-stream primitive that "
                    "would be apples-to-apples (its closest, pipes, is "
                    "a different abstraction with VFS overhead).  "
                    "Event groups and workqueues likewise have no "
                    "NuttX equivalent and are absent.\n"
                ),
            }.get(native_suite, "")
            lines.append(
                f"\n### Wrapper vs native {native_label} (within-run delta)\n"
            )
            lines.append(
                f"Each row is one binding's measurement of its own "
                f"wrapper paired against the **raw {native_label} "
                f"baseline from the same process**.  Same scheduler "
                f"state, same noise, so the Δ column is a clean "
                f"per-binding estimate of wrapper overhead.  Δ near 0 ns "
                f"⇒ binding wrapper matches raw native API within "
                f"measurement noise.\n"
            )
            if ipc_caveat:
                lines.append(ipc_caveat)
            header = ["Operation", "Binding", "Wrapper called", "Wrapper ns", "Native ns", "Δ"]
            lines.append("| " + " | ".join(header) + " |")
            lines.append("|" + "|".join("---" for _ in header) + "|")
            for row in wn_rows:
                lines.append("| " + " | ".join(row) + " |")

            if native_suite == "native_freertos":
                lines.append(
                    "\n#### Lifecycle and intrinsic-cost caveats\n"
                )
                lines.append(
                    "Per-call wrapper overhead is sub-µs for every primitive: "
                    "lock/unlock, take/give, send/receive, yield are all within "
                    "±200 ns of raw FreeRTOS.  The remaining gaps are FreeRTOS-"
                    "intrinsic costs of the underlying kernel work, **not** "
                    "wrapper-layer overhead:\n"
                )
                lines.append(
                    "- **Thread create+destroy ≈ +7 µs:** FreeRTOS task "
                    "lifecycle (`prvInitialiseNewTask` + `prvAddNewTaskToReadyList` "
                    "+ `vTaskDelete` + list cleanup) runs regardless of how thin "
                    "the wrapper is.  oveRTOS uses single-allocation static-task "
                    "creation (no extra heap blocks) and task-notification join "
                    "via a Dekker-style handshake (no separate semaphore "
                    "object).  Closing this further requires a thread-pool API "
                    "(different ownership semantics) and is out of scope for "
                    "the zero-overhead claim, which is about per-call cost.\n"
                )
                lines.append(
                    "- **Condvar signal+wait ≈ +5 µs:** POSIX-style condvar "
                    "contract requires the caller's mutex to be released "
                    "atomically with the wait and re-acquired on wake.  That "
                    "extra `xSemaphoreGive(mtx) + xSemaphoreTake(mtx)` round "
                    "trip is what the raw `ulTaskNotifyTake` baseline doesn't "
                    "pay.  Anyone wanting condvar semantics pays this; the "
                    "binding doesn't add to it.\n"
                )
                lines.append(
                    "- **Event signal+wait ≈ +2 µs:** `ove_event_*` is "
                    "implemented directly on top of FreeRTOS task "
                    "notifications (no semaphore in the middle).  The residual "
                    "gap vs raw `ulTaskNotifyTake` is the cost of going through "
                    "the wrapper function (`xTaskGetCurrentTaskHandle` lookup + "
                    "`evt->waiter` store + frame setup) on each call.  The "
                    "wrapper buys uniform single-waiter semantics across "
                    "RTOSes; the per-call cost is what it is.\n"
                )
                lines.append(
                    "- **Context switch (2t) ≈ +6 µs:** the bench runs a "
                    "full ping-pong cycle (sem give/take across two tasks).  "
                    "Both directions go through the wrapper, so the wrapper "
                    "cost adds twice; the native baseline pays the same "
                    "context-switch cost without that doubling.\n"
                )
                lines.append(
                    "- **Rust same-process native baseline elevation "
                    "(+40-65% on `native_*` rows):** `bench_native_freertos.c` "
                    "is *the same C code* compiled into every binary, so the "
                    "Rust column for those rows does not reflect any binding "
                    "behaviour.  Investigated via `CONFIG_OVE_BENCHMARK_"
                    "DISABLE_ICACHE` (toggles `SCB_DisableICache` for the "
                    "run): with I-cache off, all rows scale up ~2.5× as "
                    "expected, but the Rust↔C ratio does not converge — "
                    "the absolute gap actually widens slightly.  I-cache "
                    "pressure from Rust's larger text footprint is *not* "
                    "the dominant cause.  The remaining elevation is "
                    "binary-layout / call-frame / linker-placement noise "
                    "that varies between Rust and C process images on this "
                    "Cortex-M7; not closeable from the binding side.\n"
                )

    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", nargs="+", required=True,
                   help="bench stdout dumps to compare")
    p.add_argument("--output", default=None,
                   help="markdown report output path (default: stdout)")
    p.add_argument("--threshold-pct", type=float, default=10.0,
                   help="highlight cases where binding-vs-C exceeds this")
    args = p.parse_args()

    by_rtos = load_inputs(args.input)
    if not by_rtos:
        print("no JSON envelopes found in inputs", file=sys.stderr)
        sys.exit(1)

    report = build_report(by_rtos, args.threshold_pct)

    if args.output:
        Path(args.output).write_text(report)
        print(f"wrote {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
