#!/usr/bin/env python3

# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""Iteration-count calibration reader for oveRTOS benchmarks.

Consumes bench-stdout dumps produced with `CONFIG_OVE_BENCHMARK_NOISE_AUDIT=y`
(the per-case JSON envelope carries an `audit` array of
`{n, mean_ns, stddev_ns_q1000}` checkpoints).  For each case it computes
CV = stddev / mean at each checkpoint and emits a Markdown report
showing how CV converges with iteration count.

Used to settle the production iteration counts: pick the smallest N
where additional iterations stop reducing CV meaningfully, lock that
in via per-case `iterations` overrides or `CONFIG_OVE_BENCHMARK_ITERATIONS`,
then turn audit mode off again.

Usage:
  bench_audit.py --input <bench-stdout-or-json-file> ...
                 [--output <report.md>]
                 [--cv-threshold 2.0]
                 [--elbow-rel-improvement 5.0]

Reads the same `###BENCH_JSON_BEGIN`/`###BENCH_JSON_END` envelopes that
bench_compare.py reads.  Cases without an `audit` array are skipped.
"""

import argparse
import sys
from collections import defaultdict
from pathlib import Path

from bench_utils import extract_envelopes


def load_inputs(paths):
    """Return list of (rtos, binding, suite, case_name, audit_points).

    `audit_points` is a list of dicts with keys n / mean_ns / stddev_ns
    (already converted from the wire-format `stddev_ns_q1000` fixed-point).
    """
    rows = []
    for path in paths:
        text = Path(path).read_text()
        for env in extract_envelopes(text):
            rtos = env.get("rtos", "?")
            binding = env.get("binding", "?")
            suite = env.get("suite", "?")
            for case in env.get("cases", []):
                audit = case.get("audit")
                if not audit:
                    continue
                points = []
                for p in audit:
                    n = int(p.get("n", 0))
                    mean = float(p.get("mean_ns", 0))
                    stddev = float(p.get("stddev_ns_q1000", 0)) / 1000.0
                    points.append({"n": n, "mean_ns": mean,
                                   "stddev_ns": stddev})
                rows.append((rtos, binding, suite,
                             case.get("name", "?"), points))
    return rows


def cv_pct(point):
    if point["mean_ns"] <= 0:
        return None
    return 100.0 * point["stddev_ns"] / point["mean_ns"]


def recommend_n(points, cv_threshold, elbow_rel):
    """Pick the smallest N where additional iterations stop helping.

    Two stopping rules, take whichever fires first:
      (a) CV drops below `cv_threshold` (percent).
      (b) Doubling N from this point reduces CV by less than
          `elbow_rel` percent of its current value (the elbow).
    Returns the chosen N or None if neither rule fires by the last
    checkpoint (in which case the user should bump the audit ceiling).
    """
    if not points:
        return None
    sorted_points = sorted(points, key=lambda p: p["n"])
    for i, p in enumerate(sorted_points):
        cv = cv_pct(p)
        if cv is None:
            continue
        if cv <= cv_threshold:
            return p["n"]
        if i + 1 < len(sorted_points):
            next_cv = cv_pct(sorted_points[i + 1])
            if next_cv is None:
                continue
            if cv > 0 and (cv - next_cv) / cv * 100.0 < elbow_rel:
                return p["n"]
    return None


def build_report(rows, cv_threshold, elbow_rel):
    lines = []
    lines.append("# Iteration-count calibration report\n")
    lines.append(
        "Generated by `scripts/bench_audit.py` from oveRTOS bench runs "
        f"with `CONFIG_OVE_BENCHMARK_NOISE_AUDIT=y`.  CV = stddev / mean "
        f"× 100%.  Recommendation rule: smallest N where CV ≤ "
        f"{cv_threshold:.1f}% **or** doubling N reduces CV by less than "
        f"{elbow_rel:.1f}% of its current value.\n"
    )

    # Group by (rtos, binding, suite).
    grouped = defaultdict(list)
    for rtos, binding, suite, case_name, points in rows:
        grouped[(rtos, binding, suite)].append((case_name, points))

    # Determine the union of N checkpoints observed across all cases —
    # so the report header is consistent even when some cases have
    # fewer checkpoints (long-running cases that don't reach 10 000).
    all_ns = set()
    for _rtos, _b, _s, _c, points in rows:
        for p in points:
            all_ns.add(p["n"])
    ordered_ns = sorted(all_ns)

    # Class buckets used for the final summary recommendation.
    class_buckets = defaultdict(list)

    for (rtos, binding, suite), cases in sorted(grouped.items()):
        lines.append(f"\n## {rtos} / {binding} / {suite}\n")
        header = ["Case"] + [f"N={n}" for n in ordered_ns] + ["recommended"]
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "|".join("---" for _ in header) + "|")
        for case_name, points in cases:
            by_n = {p["n"]: p for p in points}
            row = [case_name]
            for n in ordered_ns:
                p = by_n.get(n)
                if p is None:
                    row.append("—")
                    continue
                cv = cv_pct(p)
                row.append(f"{cv:.2f}%" if cv is not None else "—")
            rec = recommend_n(points, cv_threshold, elbow_rel)
            row.append(str(rec) if rec is not None else "(>max)")
            lines.append("| " + " | ".join(row) + " |")

            cls = classify_case(case_name)
            if rec is not None:
                class_buckets[cls].append(rec)

    lines.append(
        "\n## Recommended per-class iteration counts\n"
    )
    lines.append(
        "Rule: take the **maximum** recommended N across all cases "
        "in a class (i.e. the worst-case case decides the class "
        "iteration count, so every case in the class converges).\n"
    )
    lines.append("| Class | recommended N | observed range |")
    lines.append("|---|---|---|")
    for cls in sorted(class_buckets.keys()):
        ns = class_buckets[cls]
        lines.append(
            f"| {cls} | {max(ns)} | {min(ns)}–{max(ns)} (n={len(ns)}) |"
        )

    return "\n".join(lines) + "\n"


def classify_case(case_name):
    """Bucket a case name into one of the per-class iteration buckets."""
    name = case_name.lower()
    if "delay" in name or "sleep" in name:
        return "long-running (delay/sleep)"
    if "context_switch" in name or "ctx_switch" in name:
        return "context-switch"
    if "create_destroy" in name and ("thread" in name or "workqueue" in name):
        return "thread/workqueue create+destroy"
    if "create_destroy" in name:
        return "object create+destroy"
    if "throughput" in name:
        return "throughput (2-thread)"
    return "fast latency (default)"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", nargs="+", required=True,
                   help="bench stdout dumps to process")
    p.add_argument("--output", default=None,
                   help="markdown report output path (default: stdout)")
    p.add_argument("--cv-threshold", type=float, default=2.0,
                   help="CV%% below which N is considered good enough "
                        "(default: 2.0)")
    p.add_argument("--elbow-rel-improvement", type=float, default=5.0,
                   help="if doubling N reduces CV by less than this %% "
                        "of its current value, that N is the elbow "
                        "(default: 5.0)")
    args = p.parse_args()

    rows = load_inputs(args.input)
    if not rows:
        print("no audit envelopes found in inputs (check that the bench "
              "was built with CONFIG_OVE_BENCHMARK_NOISE_AUDIT=y)",
              file=sys.stderr)
        sys.exit(1)

    report = build_report(rows, args.cv_threshold,
                          args.elbow_rel_improvement)

    if args.output:
        Path(args.output).write_text(report)
        print(f"wrote {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
