#!/usr/bin/env python3

# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""Emit a Doxygen PREDEFINED fragment from Kconfig CONFIG_OVE_* symbols.

The Doxyfiles `@INCLUDE` the generated snippet so they automatically pick
up every conditionally-compiled API surface as new modules are added to
Kconfig — without requiring a manual Doxyfile edit per module.
"""

import argparse
import re
from pathlib import Path

CONFIG_DIRS = [Path("config"), Path("apps"), Path("boards")]
DEFAULT_OUT = Path("output/docs/Doxyfile.predefined")

# Symbols that must NOT be force-defined for Doxygen.  ZERO_HEAP hides the
# heap-mode `_create()`/`_destroy()` functions via `#ifndef`; we always want
# to document the heap-mode API surface, so leave it undefined.
EXCLUDED_SYMBOLS = {"OVE_ZERO_HEAP"}


def collect_config_symbols(roots):
    """Return sorted unique set of `config OVE_*` identifiers."""
    pat = re.compile(r"^\s*config\s+(OVE_\w+)")
    names = set()
    for root in roots:
        if not root.exists():
            continue
        for f in sorted(root.rglob("Config.in*")):
            for line in f.read_text().splitlines():
                m = pat.match(line)
                if m:
                    names.add(m.group(1))
    return sorted(n for n in names if n not in EXCLUDED_SYMBOLS)


def render(symbols):
    lines = [
        "# Auto-generated by scripts/kconfig_doxyfile_gen.py — do not edit.",
        "# Defines every CONFIG_OVE_* symbol so Doxygen documents the",
        "# conditional API regardless of which modules a particular build",
        "# enables.  Re-run via `make docs`.",
        "",
        "PREDEFINED += \\",
    ]
    last = len(symbols) - 1
    for i, name in enumerate(symbols):
        sep = "" if i == last else " \\"
        lines.append(f"    CONFIG_{name}=1{sep}")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT,
                    help=f"output path (default: {DEFAULT_OUT})")
    args = ap.parse_args()

    symbols = collect_config_symbols(CONFIG_DIRS)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(symbols))
    print(f"[doxyfile-gen] {len(symbols)} CONFIG_OVE_* symbols -> "
          f"{args.output}")


if __name__ == "__main__":
    main()
