#!/usr/bin/env python3
# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""
LVGL image converter — converts PNG/JPG/BMP input files to C source
containing an `lv_image_dsc_t` descriptor ready to link and reference
from `lv::Image::src(&...)`.

Supported output formats (LVGL v9.x color formats):
  - rgb565    : 2 bytes/pixel, 16-bit RGB (no alpha).
  - rgb565a8  : 2 bytes RGB565 + 1 byte alpha trailing the RGB data.
  - rgb888    : 3 bytes/pixel in BGR order (little-endian on the wire).
  - xrgb8888  : 4 bytes/pixel in BGRX order (padding at offset 3).
  - argb8888  : 4 bytes/pixel in BGRA order.

Usage:
  lvgl_img_conv.py --input <image> --output-dir <dir>
                   --format <cf> --name <symbol>

Outputs (relative to --output-dir):
  <name>.c   — byte array + `const lv_image_dsc_t <name>`
  <name>.h   — `extern const lv_image_dsc_t <name>;` declaration
"""

import argparse
import os
import sys


FORMAT_CODE = {
    # Values match LV_COLOR_FORMAT_* enumerators in LVGL v9.2
    # (dl/lvgl/src/misc/lv_color.h).
    "rgb565":   0x12,
    "rgb565a8": 0x14,
    "rgb888":   0x0F,
    "xrgb8888": 0x11,
    "argb8888": 0x10,
}

BYTES_PER_PIXEL = {
    "rgb565":   2,
    "rgb565a8": 3,  # 2 bytes RGB + 1 byte alpha (alpha stored trailing)
    "rgb888":   3,
    "xrgb8888": 4,
    "argb8888": 4,
}


def load_image(path):
    try:
        from PIL import Image
    except ImportError:
        sys.stderr.write(
            "Error: Pillow not installed. Install with: pip install Pillow\n"
        )
        sys.exit(1)
    img = Image.open(path).convert("RGBA")
    return img


def convert_pixel_data(img, fmt):
    """Encode a Pillow RGBA image to LVGL bytes for the target format."""
    w, h = img.size
    pixels = img.load()

    data = bytearray()

    if fmt == "rgb565":
        for y in range(h):
            for x in range(w):
                r, g, b, _ = pixels[x, y]
                val = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
                data.append(val & 0xFF)
                data.append((val >> 8) & 0xFF)

    elif fmt == "rgb565a8":
        # LVGL RGB565A8 layout: all RGB565 pixels first, then all alpha bytes.
        rgb = bytearray()
        alpha = bytearray()
        for y in range(h):
            for x in range(w):
                r, g, b, a = pixels[x, y]
                val = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
                rgb.append(val & 0xFF)
                rgb.append((val >> 8) & 0xFF)
                alpha.append(a)
        data = rgb + alpha

    elif fmt == "rgb888":
        for y in range(h):
            for x in range(w):
                r, g, b, _ = pixels[x, y]
                data.append(b)
                data.append(g)
                data.append(r)

    elif fmt == "xrgb8888":
        for y in range(h):
            for x in range(w):
                r, g, b, _ = pixels[x, y]
                data.append(b)
                data.append(g)
                data.append(r)
                data.append(0xFF)

    elif fmt == "argb8888":
        for y in range(h):
            for x in range(w):
                r, g, b, a = pixels[x, y]
                data.append(b)
                data.append(g)
                data.append(r)
                data.append(a)

    else:
        raise ValueError(f"unknown format: {fmt}")

    return bytes(data)


def emit_c_file(name, fmt, img, data, out_path):
    w, h = img.size
    cf = FORMAT_CODE[fmt]
    bpp = BYTES_PER_PIXEL[fmt]
    stride = w * bpp if fmt != "rgb565a8" else w * 2
    # data_size: for rgb565a8 LVGL wants the full RGB+A length so the
    # decoder reads the alpha plane correctly.
    data_size = len(data)

    lines = []
    lines.append("/*")
    lines.append(" * Auto-generated by scripts/lvgl_img_conv.py — do not edit.")
    lines.append(f" * Source: {name}")
    lines.append(f" * Size:   {w}x{h}, format {fmt}")
    lines.append(" */")
    lines.append("")
    lines.append("#include <lvgl.h>")
    lines.append("")
    lines.append(f"static const uint8_t {name}_map[] = {{")

    # Emit bytes in 12-per-line groups for readability.
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        hex_parts = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_parts},")

    lines.append("};")
    lines.append("")
    lines.append(f"const lv_image_dsc_t {name} = {{")
    lines.append("    .header = {")
    lines.append("        .magic      = LV_IMAGE_HEADER_MAGIC,")
    lines.append(f"        .cf         = {cf},  /* LV_COLOR_FORMAT_{fmt.upper()} */")
    lines.append("        .flags      = 0,")
    lines.append(f"        .w          = {w},")
    lines.append(f"        .h          = {h},")
    lines.append(f"        .stride     = {stride},")
    lines.append("        .reserved_2 = 0,")
    lines.append("    },")
    lines.append(f"    .data_size = {data_size},")
    lines.append(f"    .data      = {name}_map,")
    lines.append("    .reserved  = NULL,")
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))


def emit_h_file(name, out_path):
    lines = []
    lines.append("/*")
    lines.append(" * Auto-generated by scripts/lvgl_img_conv.py — do not edit.")
    lines.append(" */")
    lines.append("")
    lines.append(f"#ifndef OVE_IMAGE_{name.upper()}_H")
    lines.append(f"#define OVE_IMAGE_{name.upper()}_H")
    lines.append("")
    lines.append("#include <lvgl.h>")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    lines.append(f"extern const lv_image_dsc_t {name};")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description="LVGL image converter")
    parser.add_argument("--input", required=True, help="Source image path")
    parser.add_argument("--output-dir", required=True, help="Output directory")
    parser.add_argument("--format", required=True, choices=FORMAT_CODE.keys(),
                        help="Target LVGL color format")
    parser.add_argument("--name", required=True, help="C symbol name")
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        sys.stderr.write(f"Error: input file not found: {args.input}\n")
        sys.exit(1)

    os.makedirs(args.output_dir, exist_ok=True)

    img = load_image(args.input)
    data = convert_pixel_data(img, args.format)

    c_path = os.path.join(args.output_dir, f"{args.name}.c")
    h_path = os.path.join(args.output_dir, f"{args.name}.h")

    emit_c_file(args.name, args.format, img, data, c_path)
    emit_h_file(args.name, h_path)

    print(f"  Generated: {c_path} ({img.size[0]}x{img.size[1]}, {args.format}, {len(data)} bytes)")


if __name__ == "__main__":
    main()
