# Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file is part of oveRTOS.

"""Configuration generation — absorbs genconfig.py, gen_board_desc.py, patch.py."""

import glob
import json
import os
import subprocess
import sys

from .workspace import Workspace, get_bool, get_str

try:
    from jinja2 import Environment, FileSystemLoader
except ImportError:
    Environment = None

try:
    import yaml
except ImportError:
    yaml = None

try:
    import jsonschema
except ImportError:
    jsonschema = None


# ── Config generation (from genconfig.py) ─────────────────────────────────

def render_template(env, template_name, output_path, config):
    """Render a Jinja2 template to a file."""
    try:
        template = env.get_template(template_name)
    except Exception as e:
        print(f"Error loading template {template_name}: {e}")
        sys.exit(1)

    content = template.render(config=config)
    with open(output_path, "w") as f:
        f.write(content)


def generate_configs(ws):
    """Generate configuration files from .config using Jinja2 templates."""
    if Environment is None:
        print("Error: jinja2 not installed. Install with: pip install jinja2")
        sys.exit(1)

    config = ws.config
    output_dir = ws.gen_dir
    templates_dir = os.path.join(ws.ove_dir, "config", "templates")
    os.makedirs(output_dir, exist_ok=True)

    env = Environment(
        loader=FileSystemLoader(templates_dir),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )

    # Helper functions available in templates
    env.globals["get_bool"] = lambda k, d=False: get_bool(config, k, d)
    from .workspace import get_int
    env.globals["get_int"] = lambda k, d=0: get_int(config, k, d)
    env.globals["get_str"] = lambda k, d="": get_str(config, k, d)
    env.globals["config"] = config

    # Always generate core config files
    render_template(env, "ove_config.h.j2",
                    os.path.join(output_dir, "ove_config.h"), config)
    print(f"  Generated: {output_dir}/ove_config.h")

    render_template(env, "ove_config.cmake.j2",
                    os.path.join(output_dir, "ove_config.cmake"), config)
    print(f"  Generated: {output_dir}/ove_config.cmake")

    # RTOS-specific config
    if get_bool(config, "CONFIG_OVE_RTOS_FREERTOS"):
        render_template(env, "FreeRTOSConfig.h.j2",
                        os.path.join(output_dir, "FreeRTOSConfig.h"), config)
        print(f"  Generated: {output_dir}/FreeRTOSConfig.h")

    elif get_bool(config, "CONFIG_OVE_RTOS_ZEPHYR"):
        render_template(env, "prj.conf.j2",
                        os.path.join(output_dir, "prj.conf"), config)
        print(f"  Generated: {output_dir}/prj.conf")

    elif get_bool(config, "CONFIG_OVE_RTOS_NUTTX"):
        render_template(env, "nuttx_defconfig.j2",
                        os.path.join(output_dir, "nuttx_defconfig"), config)
        print(f"  Generated: {output_dir}/nuttx_defconfig")
        render_template(env, "ove_sources.mk.j2",
                        os.path.join(output_dir, "ove_sources.mk"), config)
        print(f"  Generated: {output_dir}/ove_sources.mk")

    # Generate model C arrays from .tflite files (needed by NuttX and
    # any other Make-based build that doesn't call OveModels.cmake).
    if get_bool(config, "CONFIG_OVE_INFER"):
        model_dir = os.path.join(ws.ove_dir, "models")
        gen_models_dir = os.path.join(output_dir, "generated_models")
        convert_script = os.path.join(model_dir, "convert.py")
        if os.path.isdir(model_dir) and os.path.isfile(convert_script):
            import glob
            tflite_files = glob.glob(os.path.join(model_dir, "**/*.tflite"),
                                     recursive=True)
            if tflite_files:
                os.makedirs(gen_models_dir, exist_ok=True)
                import subprocess
                result = subprocess.run(
                    [sys.executable, convert_script,
                     "--model-dir", model_dir,
                     "--output-dir", gen_models_dir],
                    capture_output=True, text=True)
                if result.returncode == 0:
                    print(f"  Generated: {gen_models_dir}/ "
                          f"({len(tflite_files)} models)")
                else:
                    print(f"  Warning: model conversion failed: "
                          f"{result.stderr.strip()}")

    print("Config generation complete.")


# ── Board descriptor generation (from gen_board_desc.py) ──────────────────

def _c_str(s):
    """Escape a string for use in a C string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _generate_board_desc_header(board):
    """Generate board_desc.h content from parsed board YAML."""
    lines = []
    lines.append("/*")
    lines.append(" * Auto-generated by gen_board_desc.py -- do not edit.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef OVE_BOARD_DESC_H")
    lines.append("#define OVE_BOARD_DESC_H")
    lines.append("")

    b = board["board"]
    lines.append("/* Board identity */")
    lines.append(f'#define OVE_BOARD_NAME       "{_c_str(b["name"])}"')
    lines.append(f'#define OVE_BOARD_MCU_FAMILY "{_c_str(b["mcu_family"])}"')
    lines.append(f'#define OVE_BOARD_MCU        "{_c_str(b["mcu"])}"')
    lines.append("")

    if "clock" in board:
        clk = board["clock"]
        lines.append("/* Clock configuration */")
        for key in ["hse_freq_mhz", "sysclk_mhz", "ahb_div", "apb1_div",
                     "apb2_div"]:
            if key in clk:
                lines.append(
                    f"#define OVE_CLOCK_{key.upper()} {clk[key]}")
        lines.append("")

    if "memory" in board:
        mem = board["memory"]
        lines.append("/* Memory layout */")
        for key in ["flash_kb", "ram_kb", "dtcm_kb", "sdram_kb"]:
            if key in mem:
                lines.append(
                    f"#define OVE_MEMORY_{key.upper()} {mem[key]}")
        if "sdram_start" in mem:
            lines.append(
                f"#define OVE_MEMORY_SDRAM_START {mem['sdram_start']}")
        lines.append("")

    gpio = board.get("gpio", {})
    lines.append("/* GPIO configuration */")
    lines.append(
        f"#define OVE_GPIO_PORT_COUNT    "
        f"{gpio.get('port_count', 0)}")
    lines.append(
        f"#define OVE_GPIO_PINS_PER_PORT "
        f"{gpio.get('pins_per_port', 16)}")
    lines.append("")

    if "leds" in board:
        leds = board["leds"]
        lines.append("/* LED configuration */")
        lines.append(f"#define OVE_LED_COUNT {len(leds)}")
        for i, led in enumerate(leds):
            prefix = f"OVE_LED{i}"
            lines.append(f"#define {prefix}_PORT       {led['port']}")
            lines.append(f"#define {prefix}_PIN        {led['pin']}")
            active_low = 1 if led.get("active_low", False) else 0
            lines.append(f"#define {prefix}_ACTIVE_LOW {active_low}")
        lines.append("")

    if "audio" in board:
        audio = board["audio"]
        if "i2s" in audio:
            i2s = audio["i2s"]
            lines.append("/* Audio I2S configuration */")
            for key in ["sample_rate", "bit_depth", "channels",
                        "buffer_samples"]:
                if key in i2s:
                    lines.append(
                        f"#define OVE_AUDIO_I2S_{key.upper()} "
                        f"{i2s[key]}")
            lines.append("")
        if "codec" in audio:
            codec = audio["codec"]
            lines.append("/* Audio codec configuration */")
            if "type" in codec:
                lines.append(
                    f'#define OVE_AUDIO_CODEC_TYPE '
                    f'"{_c_str(codec["type"])}"')
            if "i2c_addr" in codec:
                lines.append(
                    f"#define OVE_AUDIO_CODEC_I2C_ADDR "
                    f"{codec['i2c_addr']}")
            lines.append("")

    if "display" in board:
        disp = board["display"]
        lines.append("/* Display configuration */")
        if "width" in disp:
            lines.append(f"#define OVE_DISPLAY_WIDTH  {disp['width']}")
        if "height" in disp:
            lines.append(f"#define OVE_DISPLAY_HEIGHT {disp['height']}")
        if "color_format" in disp:
            lines.append(
                f'#define OVE_DISPLAY_COLOR_FORMAT '
                f'"{_c_str(disp["color_format"])}"')
        lines.append("")

    if "serial" in board:
        serial = board["serial"]
        if "console" in serial:
            con = serial["console"]
            lines.append("/* Serial console configuration */")
            if "baud" in con:
                lines.append(
                    f"#define OVE_SERIAL_CONSOLE_BAUD {con['baud']}")
            if "tx_pin" in con:
                lines.append(
                    f'#define OVE_SERIAL_CONSOLE_TX_PIN '
                    f'"{_c_str(con["tx_pin"])}"')
            if "rx_pin" in con:
                lines.append(
                    f'#define OVE_SERIAL_CONSOLE_RX_PIN '
                    f'"{_c_str(con["rx_pin"])}"')
            if "rx_buffer_size" in con:
                lines.append(
                    f"#define OVE_SERIAL_CONSOLE_RX_BUFFER_SIZE "
                    f"{con['rx_buffer_size']}")
            lines.append("")

    if "sdcard" in board:
        sd = board["sdcard"]
        lines.append("/* SD card configuration */")
        if "interface" in sd:
            lines.append(
                f'#define OVE_SDCARD_INTERFACE '
                f'"{_c_str(sd["interface"])}"')
        lines.append("")

    if "watchdog" in board:
        wd = board["watchdog"]
        lines.append("/* Watchdog configuration */")
        if "timeout_ms" in wd:
            lines.append(
                f"#define OVE_WATCHDOG_TIMEOUT_MS {wd['timeout_ms']}")
        lines.append("")

    # Runtime descriptor struct
    lines.append("/* Runtime board descriptor */")
    lines.append('#include "ove/board_types.h"')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    led_count = len(board.get("leds", []))
    if led_count > 0:
        lines.append(
            f"static const struct ove_led_desc "
            f"ove_board_leds[{led_count}] = {{")
        for led in board["leds"]:
            active_low = 1 if led.get("active_low", False) else 0
            lines.append(
                f"    {{ {led['port']}, {led['pin']}, {active_low} }},")
        lines.append("};")
    else:
        lines.append(
            "#define ove_board_leds "
            "((const struct ove_led_desc *)0)")
    lines.append("")

    gpio_port_count = board.get("gpio", {}).get("port_count", 0)
    gpio_pins_per_port = board.get("gpio", {}).get("pins_per_port", 16)

    lines.append(
        "static const struct ove_board_desc "
        "ove_board_descriptor = {")
    lines.append('    .name = OVE_BOARD_NAME,')
    lines.append('    .mcu_family = OVE_BOARD_MCU_FAMILY,')
    lines.append('    .mcu = OVE_BOARD_MCU,')
    lines.append(f"    .gpio_port_count = {gpio_port_count},")
    lines.append(f"    .gpio_pins_per_port = {gpio_pins_per_port},")
    lines.append(f"    .led_count = {led_count},")
    lines.append("    .leds = ove_board_leds,")
    lines.append("};")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* OVE_BOARD_DESC_H */")
    lines.append("")

    return "\n".join(lines)


def generate_board_desc(ws):
    """Generate board_desc.h from board.yaml if available."""
    board_dir = ws.board_dir
    if not board_dir:
        return

    board_yaml_path = os.path.join(board_dir, "board.yaml")
    if not os.path.isfile(board_yaml_path):
        return

    if yaml is None:
        print("Warning: pyyaml not installed, skipping board descriptor")
        return

    print("=== Generating board descriptor ===")
    with open(board_yaml_path) as f:
        board = yaml.safe_load(f)

    # Validate against schema
    schema_path = os.path.join(ws.ove_dir, "config", "schemas",
                               "board_schema.json")
    if jsonschema and os.path.isfile(schema_path):
        with open(schema_path) as f:
            schema = json.load(f)
        board_clean = {k: v for k, v in board.items() if k != "_meta"}
        try:
            jsonschema.validate(instance=board_clean, schema=schema)
        except jsonschema.ValidationError as e:
            print(f"Board YAML validation error: {e.message}")
            sys.exit(1)

    header = _generate_board_desc_header(board)
    output_path = os.path.join(ws.gen_dir, "board_desc.h")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header)
    print(f"  Generated: {output_path}")


# ── Patch application (from patch.py) ─────────────────────────────────────

def apply_patches(patch_dir, target_dir, name):
    """Apply all numbered .patch files from patch_dir to target_dir."""
    if not os.path.isdir(patch_dir):
        return True

    patches = sorted(glob.glob(os.path.join(patch_dir, "*.patch")))
    if not patches:
        print(f"  {name}: no patches to apply")
        return True

    sentinel = os.path.join(target_dir, ".ove_patched")
    if os.path.isfile(sentinel):
        print(f"  {name}: patches already applied")
        return True

    print(f"  {name}: applying {len(patches)} patch(es)...")
    for p in patches:
        pname = os.path.basename(p)
        ret = subprocess.run(
            ["patch", "-p1", "-d", target_dir, "-i", os.path.abspath(p)],
            capture_output=True, text=True)
        if ret.returncode != 0:
            print(f"  ERROR: patch {pname} failed:")
            print(f"  {ret.stderr}")
            return False
        print(f"    Applied: {pname}")

    with open(sentinel, "w") as f:
        f.write("patched\n")
    return True


def apply_all_patches(ws):
    """Apply patches based on RTOS selection."""
    config = ws.config
    board_name = ws.board_name
    if not board_name:
        print("Error: CONFIG_OVE_BOARD_NAME not set in .config")
        sys.exit(1)

    board_base = os.path.join(ws.ove_dir, "boards", board_name)

    print("Applying patches...")
    ok = True

    if get_bool(config, "CONFIG_OVE_RTOS_FREERTOS"):
        stm32cube = os.path.join(ws.ws_dl_dir, "STM32CubeF7")
        if os.path.isdir(stm32cube):
            ok = apply_patches(
                os.path.join(board_base, "freertos", "patches"),
                stm32cube, "STM32CubeF7") and ok
        lvgl = os.path.join(ws.ws_dl_dir, "lvgl")
        if os.path.isdir(lvgl):
            ok = apply_patches(
                os.path.join(board_base, "freertos", "patches"),
                lvgl, "LVGL") and ok

    elif get_bool(config, "CONFIG_OVE_RTOS_ZEPHYR"):
        zephyr = os.path.join(ws.ws_dl_dir, "zephyr-workspace")
        if os.path.isdir(zephyr):
            ok = apply_patches(
                os.path.join(board_base, "zephyr", "patches"),
                zephyr, "Zephyr") and ok

    elif get_bool(config, "CONFIG_OVE_RTOS_NUTTX"):
        nuttx = os.path.join(ws.ws_dl_dir, "nuttx")
        if os.path.isdir(nuttx):
            ok = apply_patches(
                os.path.join(board_base, "nuttx", "patches"),
                nuttx, "NuttX") and ok

    elif get_bool(config, "CONFIG_OVE_RTOS_POSIX"):
        print("  POSIX: no patches needed")

    if not ok:
        print("\nSome patches failed to apply.")
        sys.exit(1)
    print("\nAll patches applied successfully.")


# ── Image pipeline (PNG → lv_image_dsc_t) ─────────────────────────────────

def _find_board_lv_conf(ws):
    """Locate the board's lv_conf.h for LV_COLOR_DEPTH discovery.

    Returns the absolute path or None if not found. Searches the same
    candidate locations that `config/cmake/ove_rust.cmake` uses.
    """
    candidates = []
    if ws.rtos == "posix":
        candidates.append(os.path.join(
            ws.ove_dir, "boards", "host", "posix", "lv_conf.h"))
        candidates.append(os.path.join(
            ws.ove_dir, "boards", "wasm", "posix", "lv_conf.h"))
    board_dir = getattr(ws, "board_dir", None) or (
        os.path.join(ws.ove_dir, "boards", ws.board_name or "")
        if ws.board_name else None)
    if board_dir:
        rtos = ws.rtos or "posix"
        for sub in (rtos, f"{rtos}/inc", "inc", "freertos/inc"):
            candidates.append(os.path.join(board_dir, sub, "lv_conf.h"))
        candidates.append(os.path.join(board_dir, "lv_conf.h"))

    for c in candidates:
        if c and os.path.isfile(c):
            return c
    return None


def _parse_lv_color_depth(lv_conf_path):
    """Parse `#define LV_COLOR_DEPTH <n>` from the given header."""
    if not lv_conf_path or not os.path.isfile(lv_conf_path):
        return None
    try:
        with open(lv_conf_path) as f:
            for line in f:
                line = line.strip()
                if line.startswith("#define") and "LV_COLOR_DEPTH" in line:
                    parts = line.split()
                    if len(parts) >= 3:
                        try:
                            return int(parts[2])
                        except ValueError:
                            pass
    except OSError:
        pass
    return None


def _pick_image_format(color_depth):
    """Map LVGL color depth to a converter format name."""
    if color_depth == 16:
        return "rgb565"
    if color_depth == 24:
        return "rgb888"
    # 32-bit default — use XRGB8888 for opaque images and rely on
    # runtime upcast for transparency if the user supplies a PNG with
    # alpha. (argb8888 would double RAM cost on everything.)
    return "xrgb8888"


def _image_symbol_name(path):
    """Derive a C symbol name from an image path."""
    base = os.path.basename(path)
    name = os.path.splitext(base)[0]
    safe = "".join(c if c.isalnum() else "_" for c in name)
    if safe and safe[0].isdigit():
        safe = "_" + safe
    return safe


def _process_app_images(ws, app, app_dir):
    """Convert every image listed in app.yaml to a C array.

    Returns a list of absolute paths to the generated .c files (to be
    emitted as APP_GENERATED_SOURCES in app_sources.cmake).
    """
    images = app.get("images") or []
    if not images:
        return []

    lv_conf_path = _find_board_lv_conf(ws)
    color_depth = _parse_lv_color_depth(lv_conf_path) or 32
    fmt = _pick_image_format(color_depth)

    gen_images_dir = os.path.join(ws.gen_dir, "generated_images")
    os.makedirs(gen_images_dir, exist_ok=True)

    convert_script = os.path.join(
        ws.ove_dir, "scripts", "lvgl_img_conv.py")
    if not os.path.isfile(convert_script):
        print(f"Warning: image converter missing at {convert_script}")
        return []

    print("=== Generating image assets ===")
    print(f"  Format: {fmt} (LV_COLOR_DEPTH={color_depth})")

    generated_c = []
    h_symbols = []
    for rel_path in images:
        abs_path = rel_path if os.path.isabs(rel_path) else \
            os.path.join(app_dir, rel_path)
        if not os.path.isfile(abs_path):
            print(f"  Error: image not found: {abs_path}")
            sys.exit(1)
        sym = _image_symbol_name(rel_path)
        result = subprocess.run(
            [sys.executable, convert_script,
             "--input", abs_path,
             "--output-dir", gen_images_dir,
             "--format", fmt,
             "--name", sym],
            capture_output=True, text=True)
        if result.returncode != 0:
            print(f"  Error converting {abs_path}:")
            print(result.stderr.strip())
            sys.exit(1)
        if result.stdout:
            print(result.stdout.rstrip())
        generated_c.append(os.path.join(gen_images_dir, f"{sym}.c"))
        h_symbols.append(sym)

    # Emit an aggregate header users can `#include "generated_images/lvgl_images.h"`.
    agg_h = os.path.join(gen_images_dir, "lvgl_images.h")
    with open(agg_h, "w") as f:
        f.write("/* Auto-generated by ove configure — do not edit. */\n")
        f.write("#ifndef OVE_LVGL_IMAGES_H\n")
        f.write("#define OVE_LVGL_IMAGES_H\n")
        for sym in h_symbols:
            f.write(f'#include "{sym}.h"\n')
        f.write("#endif\n")

    # Emit a Rust glue module with extern declarations so Rust apps can
    # pull the images in via `include!(...)` from their lib.rs. Outer
    # attributes only — `include!` into a module rejects inner attrs.
    agg_rs = os.path.join(gen_images_dir, "lvgl_images.rs")
    with open(agg_rs, "w") as f:
        f.write("// Auto-generated by ove configure — do not edit.\n\n")
        f.write("use ove::ffi::lv_image_dsc_t;\n\n")
        f.write("unsafe extern \"C\" {\n")
        for sym in h_symbols:
            f.write(f"    #[allow(non_upper_case_globals)]\n")
            f.write(f"    pub static {sym}: lv_image_dsc_t;\n")
        f.write("}\n")

    print(f"  Generated: {gen_images_dir}/ ({len(images)} images)")
    return generated_c


# ── App source generation (from app.yaml) ────────────────────────────────

def generate_app_sources(ws):
    """Generate app_sources.mk and app_sources.cmake from app.yaml."""
    app_dir = ws.app_dir
    if not app_dir:
        return

    app_yaml_path = os.path.join(app_dir, "app.yaml")
    if not os.path.isfile(app_yaml_path):
        return

    if yaml is None:
        print("Warning: pyyaml not installed, skipping app source generation")
        return

    print("=== Generating app build files ===")
    with open(app_yaml_path) as f:
        app = yaml.safe_load(f)

    # Validate against schema
    schema_path = os.path.join(ws.ove_dir, "config", "schemas",
                               "app_schema.json")
    if jsonschema and os.path.isfile(schema_path):
        with open(schema_path) as f:
            schema = json.load(f)
        try:
            jsonschema.validate(instance=app, schema=schema)
        except jsonschema.ValidationError as e:
            print(f"App YAML validation error: {e.message}")
            sys.exit(1)

    # Resolve platform/board-specific sources
    platform_sources = app.pop("platform_sources", None)
    board_sources = app.pop("board_sources", None)
    if platform_sources or board_sources:
        rtos = ws.rtos or "posix"
        board = ws.board_name or ""
        # Board-specific sources take priority over platform-specific
        if board_sources and board in board_sources:
            extra = board_sources[board]
        elif platform_sources:
            if rtos in platform_sources:
                extra = platform_sources[rtos]
            elif "default" in platform_sources:
                extra = platform_sources["default"]
            else:
                extra = []
        else:
            extra = []
        app.setdefault("sources", [])
        app["sources"] = list(app["sources"]) + extra

    # Normalize defaults
    if app.get("lang") == "rust":
        app.setdefault("rust", {})
        app["rust"].setdefault("crate_dir", ".")
    elif app.get("lang") == "zig":
        app.setdefault("zig", {})
        app["zig"].setdefault("src_dir", "src")

    # Process images → generated lv_image_dsc_t C arrays
    generated_image_sources = _process_app_images(ws, app, app_dir)
    if generated_image_sources:
        app["generated_image_sources"] = generated_image_sources

    if Environment is None:
        print("Warning: jinja2 not installed, skipping app source generation")
        return

    templates_dir = os.path.join(ws.ove_dir, "config", "templates")
    env = Environment(
        loader=FileSystemLoader(templates_dir),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )

    # Render app_sources.mk
    mk_template = env.get_template("app_sources.mk.j2")
    mk_content = mk_template.render(app=app)
    mk_path = os.path.join(ws.gen_dir, "app_sources.mk")
    with open(mk_path, "w") as f:
        f.write(mk_content)
    print(f"  Generated: {mk_path}")

    # Render app_sources.cmake
    cmake_template = env.get_template("app_sources.cmake.j2")
    cmake_content = cmake_template.render(app=app)
    cmake_path = os.path.join(ws.gen_dir, "app_sources.cmake")
    with open(cmake_path, "w") as f:
        f.write(cmake_content)
    print(f"  Generated: {cmake_path}")


# ── Combined configure command ────────────────────────────────────────────

def configure_all(ws):
    """Run full configuration: board desc + app sources + template generation."""
    ws.require_config()
    ws.ensure_dirs()
    generate_board_desc(ws)
    generate_app_sources(ws)
    print("=== Generating configuration ===")
    generate_configs(ws)


def cmd_configure(args):
    """CLI entry point for 'ove configure'."""
    ws = Workspace()
    configure_all(ws)
