#!/bin/sh
# Bundle dashboard HTML with inline CSS/JS, gzip, and convert to C header.
# Usage: ./bundle.sh <output_header>
#
# Called by CMake at build time. Requires: python3, gzip, xxd.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${1:-${SCRIPT_DIR}/../ove_net_httpd_ui_gz.h}"

TMPHTML=$(mktemp)
TMPGZ=$(mktemp)
trap 'rm -f "$TMPHTML" "$TMPGZ"' EXIT

# Inline CSS/JS into HTML using Python (safe for multi-line content)
python3 -c "
import sys, os
d = '$SCRIPT_DIR'
html   = open(os.path.join(d, 'index.html')).read()
style  = open(os.path.join(d, 'style.css')).read()
alpine = open(os.path.join(d, 'vendor', 'alpine.min.js')).read()
app    = open(os.path.join(d, 'app.js')).read()
html = html.replace('@@STYLE@@', style)
html = html.replace('@@ALPINE@@', alpine)
html = html.replace('@@APP@@', app)
sys.stdout.write(html)
" > "$TMPHTML"

# Gzip compress
gzip -9 -c "$TMPHTML" > "$TMPGZ"

# Convert to C header
cat > "$OUT" <<'HEADER'
#ifndef OVE_NET_HTTPD_UI_GZ_H
#define OVE_NET_HTTPD_UI_GZ_H

#include <stddef.h>

/*
 * Auto-generated by httpd_ui/bundle.sh -- do not edit.
 * Source: index.html + style.css + app.js + alpine.min.js
 * Content-Encoding: gzip
 */

HEADER

xxd -i "$TMPGZ" | \
    sed 's/unsigned char [^ ]*/static const unsigned char httpd_dashboard_gz[]/' | \
    sed 's/unsigned int [^ ]*/static const size_t httpd_dashboard_gz_len/' \
    >> "$OUT"

echo "" >> "$OUT"
echo "#endif /* OVE_NET_HTTPD_UI_GZ_H */" >> "$OUT"
